def random_number(min, max)
  rand(min..max)
end

hash = [
  { name: 'Alveley Wolves FC', league: 'Premier League' },
  { name: 'Liverwolves', league: 'Premier League' },
  { name: 'Dublin FC', league: 'Premier League' },
  { name: 'Munich Rovers', league: 'Premier League' },
  { name: 'Paris Rovers', league: 'Premier League' },
  { name: 'Cologne Town', league: 'Premier League' },
  { name: 'Berlin City', league: 'Premier League' },
  { name: 'Barcelona City', league: 'Premier League' },
  { name: 'Brussels FC', league: 'Premier League' },
  { name: 'Madrid Rovers', league: 'Premier League' },
  { name: 'Glasgow City FC', league: 'Premier League' },
  { name: 'Sofia Utd', league: 'Premier League' },
  { name: 'Rome Athletic', league: 'Premier League' },
  { name: 'Belfast Wednesday', league: 'Premier League' },
  { name: 'Barcelona Wanderers', league: 'Premier League' },
  { name: 'Milan Fc', league: 'Premier League' },
  { name: 'Edinburgh FC', league: 'Premier League' },
  { name: 'London Town FC', league: 'Premier League' },
  { name: 'Notttingham Utd', league: 'Premier League' },
  { name: 'Birmingham Town', league: 'Premier League' },
  { name: 'Wycombe Wolves FC', league: 'Championship' },
  { name: 'Arsenspurs FC', league: 'Championship' },
  { name: 'Gloucester FC', league: 'Championship' },
  { name: 'Kidderminter Rovers', league: 'Championship' },
  { name: 'Paris Utd', league: 'Championship' },
  { name: 'Colchester Town', league: 'Championship' },
  { name: 'Bognor City', league: 'Championship' },
  { name: 'Bangor City', league: 'Championship' },
  { name: 'Burnley Rovers FC', league: 'Championship' },
  { name: 'Leicester Rovers', league: 'Championship' },
  { name: 'Cardiff FC', league: 'Championship' },
  { name: 'Aberdeen', league: 'Championship' },
  { name: 'Naples Fc', league: 'Championship' },
  { name: 'Belfast Athletic', league: 'Championship' },
  { name: 'Luton Wanderers', league: 'Championship' },
  { name: 'Milan Juniors FC', league: 'Championship' },
  { name: 'Edinburgh Utd', league: 'Championship' },
  { name: 'London City', league: 'Championship' },
  { name: 'Notttingham Rovers', league: 'Championship' },
  { name: 'Bridgnorth Town FC', league: 'Championship' }
]

hash.each do |hash|
  Club.create(
    name: hash[:name],
    ground_name: 'Stadium',
    stand_n_name: 'North Stand',
    stand_s_name: 'South Stand',
    stand_e_name: 'East Stand',
    stand_w_name: 'West Stand',
    stand_n_condition: random_number(3, 10),
    stand_s_condition: random_number(3, 10),
    stand_e_condition: random_number(3, 10),
    stand_w_condition: random_number(3, 10),
    stand_n_capacity: random_number(5000, 10000),
    stand_s_capacity: random_number(5000, 10000),
    stand_e_capacity: random_number(5000, 10000),
    stand_w_capacity: random_number(5000, 10000),
    pitch: random_number(3, 10),
    hospitality: random_number(3, 10),
    facilities: random_number(3, 10),
    staff_fitness: random_number(3, 10),
    staff_gkp: random_number(4, 12),
    staff_dfc: random_number(4, 12),
    staff_mid: random_number(4, 12),
    staff_att: random_number(4, 12),
    staff_scouts: random_number(4, 12),
    color_primary: 'green',
    color_secondary: 'yellow',
    bank_bal: random_number(50000000, 120000000),
    league: hash[:league]
  )
end
