def random_number(min, max)
  rand(min..max)
end

hash = [
  { code: 1, name: 'Alveley Wolves FC', league: 'Premier League' },
  { code: 2, name: 'Liverwolves', league: 'Premier League' },
  { code: 3, name: 'Dublin FC', league: 'Premier League' },
  { code: 4, name: 'Munich Rovers', league: 'Premier League' },
  { code: 5, name: 'Paris Rovers', league: 'Premier League' },
  { code: 6, name: 'Cologne Town', league: 'Premier League' },
  { code: 7, name: 'Berlin City', league: 'Premier League' },
  { code: 8, name: 'Barcelona City', league: 'Premier League' },
  { code: 9, name: 'Brussels FC', league: 'Premier League' },
  { code: 10, name: 'Madrid Rovers', league: 'Premier League' },
  { code: 11, name: 'Glasgow City FC', league: 'Premier League' },
  { code: 12, name: 'Sofia Utd', league: 'Premier League' },
  { code: 13, name: 'Rome Athletic', league: 'Premier League' },
  { code: 14, name: 'Belfast Wednesday', league: 'Premier League' },
  { code: 15, name: 'Barcelona Wanderers', league: 'Premier League' },
  { code: 16, name: 'Milan Fc', league: 'Premier League' },
  { code: 17, name: 'Edinburgh FC', league: 'Premier League' },
  { code: 18, name: 'London Town FC', league: 'Premier League' },
  { code: 19, name: 'Notttingham Utd', league: 'Premier League' },
  { code: 20, name: 'Birmingham Town', league: 'Premier League' },
  { code: 21, name: 'Wycombe Wolves FC', league: 'Championship' },
  { code: 22, name: 'Arsenspurs FC', league: 'Championship' },
  { code: 23, name: 'Gloucester FC', league: 'Championship' },
  { code: 24, name: 'Kidderminter Rovers', league: 'Championship' },
  { code: 25, name: 'Paris Utd', league: 'Championship' },
  { code: 26, name: 'Colchester Town', league: 'Championship' },
  { code: 27, name: 'Bognor City', league: 'Championship' },
  { code: 28, name: 'Bangor City', league: 'Championship' },
  { code: 29, name: 'Burnley Rovers FC', league: 'Championship' },
  { code: 30, name: 'Leicester Rovers', league: 'Championship' },
  { code: 31, name: 'Cardiff FC', league: 'Championship' },
  { code: 32, name: 'Aberdeen', league: 'Championship' },
  { code: 33, name: 'Naples Fc', league: 'Championship' },
  { code: 34, name: 'Belfast Athletic', league: 'Championship' },
  { code: 35, name: 'Luton Wanderers', league: 'Championship' },
  { code: 36, name: 'Milan Juniors FC', league: 'Championship' },
  { code: 37, name: 'Edinburgh Utd', league: 'Championship' },
  { code: 38, name: 'London City', league: 'Championship' },
  { code: 39, name: 'Notttingham Rovers', league: 'Championship' },
  { code: 40, name: 'Bridgnorth Town FC', league: 'Championship' }
]

hash.each do |hash|
  Club.create(
    abbreviation: hash[:code],
    name: hash[:name],
    ground_name: 'Stadium',
    stand_n_name: 'North Stand',
    stand_s_name: 'South Stand',
    stand_e_name: 'East Stand',
    stand_w_name: 'West Stand',
    stand_n_condition: random_number(3, 10),
    stand_s_condition: random_number(3, 10),
    stand_e_condition: random_number(3, 10),
    stand_w_condition: random_number(3, 10),
    stand_n_capacity: random_number(5000, 10000),
    stand_s_capacity: random_number(5000, 10000),
    stand_e_capacity: random_number(5000, 10000),
    stand_w_capacity: random_number(5000, 10000),
    pitch: random_number(3, 10),
    hospitality: random_number(3, 10),
    facilities: random_number(3, 10),
    staff_fitness: random_number(3, 10),
    staff_gkp: random_number(4, 12),
    staff_dfc: random_number(4, 12),
    staff_mid: random_number(4, 12),
    staff_att: random_number(4, 12),
    staff_scouts: random_number(4, 12),
    color_primary: 'green',
    color_secondary: 'yellow',
    bank_bal: random_number(50000000, 120000000),
    league: hash[:league]
  )
end
