def random_number(min, max)
  rand(min..max)
end

hash = [
  { code: '001', name: 'Alveley Wolves FC', league: 'Premier League' },
  { code: '002', name: 'Liverwolves', league: 'Premier League' },
  { code: '003', name: 'Dublin FC', league: 'Premier League' },
  { code: '004', name: 'Munich Rovers', league: 'Premier League' },
  { code: '005', name: 'Paris Rovers', league: 'Premier League' },
  { code: '006', name: 'Cologne Town', league: 'Premier League' },
  { code: '007', name: 'Berlin City', league: 'Premier League' },
  { code: '008', name: 'Barcelona City', league: 'Premier League' },
  { code: '009', name: 'Brussels FC', league: 'Premier League' },
  { code: '010', name: 'Madrid Rovers', league: 'Premier League' },
  { code: '011', name: 'Glasgow City FC', league: 'Premier League' },
  { code: '012', name: 'Sofia Utd', league: 'Premier League' },
  { code: '013', name: 'Rome Athletic', league: 'Premier League' },
  { code: '014', name: 'Belfast Wednesday', league: 'Premier League' },
  { code: '015', name: 'Barcelona Wanderers', league: 'Premier League' },
  { code: '016', name: 'Milan Fc', league: 'Premier League' },
  { code: '017', name: 'Edinburgh FC', league: 'Premier League' },
  { code: '018', name: 'London Town FC', league: 'Premier League' },
  { code: '019', name: 'Notttingham Utd', league: 'Premier League' },
  { code: '020', name: 'Birmingham Town', league: 'Premier League' },
  { code: '101', name: 'Wycombe Wolves FC', league: 'Championship' },
  { code: '102', name: 'Arsenspurs FC', league: 'Championship' },
  { code: '103', name: 'Gloucester FC', league: 'Championship' },
  { code: '104', name: 'Kidderminter Rovers', league: 'Championship' },
  { code: '105', name: 'Paris Utd', league: 'Championship' },
  { code: '106', name: 'Colchester Town', league: 'Championship' },
  { code: '107', name: 'Bognor City', league: 'Championship' },
  { code: '108', name: 'Bangor City', league: 'Championship' },
  { code: '109', name: 'Burnley Rovers FC', league: 'Championship' },
  { code: '110', name: 'Leicester Rovers', league: 'Championship' },
  { code: '111', name: 'Cardiff FC', league: 'Championship' },
  { code: '112', name: 'Aberdeen', league: 'Championship' },
  { code: '113', name: 'Naples Fc', league: 'Championship' },
  { code: '114', name: 'Belfast Athletic', league: 'Championship' },
  { code: '115', name: 'Luton Wanderers', league: 'Championship' },
  { code: '116', name: 'Milan Juniors FC', league: 'Championship' },
  { code: '117', name: 'Edinburgh Utd', league: 'Championship' },
  { code: '118', name: 'London City', league: 'Championship' },
  { code: '119', name: 'Notttingham Rovers', league: 'Championship' },
  { code: '120', name: 'Bridgnorth Town FC', league: 'Championship' }
]

hash.each do |hash|
  Club.create(
    abbreviation: hash[:code],
    name: hash[:name],
    ground_name: 'Stadium',
    stand_n_name: 'North Stand',
    stand_s_name: 'South Stand',
    stand_e_name: 'East Stand',
    stand_w_name: 'West Stand',
    stand_n_condition: random_number(3, 10),
    stand_s_condition: random_number(3, 10),
    stand_e_condition: random_number(3, 10),
    stand_w_condition: random_number(3, 10),
    stand_n_capacity: random_number(2000, 10000),
    stand_s_capacity: random_number(2000, 10000),
    stand_e_capacity: random_number(2000, 10000),
    stand_w_capacity: random_number(2000, 10000),
    pitch: random_number(3, 10),
    hospitality: random_number(3, 10),
    facilities: random_number(3, 10),
    staff_fitness: random_number(3, 10),
    staff_gkp: random_number(4, 12),
    staff_dfc: random_number(4, 12),
    staff_mid: random_number(4, 12),
    staff_att: random_number(4, 12),
    staff_scouts: random_number(4, 12),
    color_primary: 'green',
    color_secondary: 'yellow',
    bank_bal: random_number(50000000, 120000000),
    league: hash[:league]
  )
end
