# Define a method to generate a random number between min and max (inclusive)
def random_number(min, max)
  rand(min..max)
end

Club.create(
  name: 'unmanaged',
  ground_name: 'Stadium',
  stand_n_name: 'n Stand',
  stand_s_name: 's Stand',
  stand_e_name: 'e Stand',
  stand_w_name: 'w Stand',
  stand_n_condition: 0,
  stand_s_condition: 0,
  stand_e_condition: 0,
  stand_w_condition: 0,
  stand_n_capacity: 0,
  stand_s_capacity: 0,
  stand_e_capacity: 0,
  stand_w_capacity: 0,
  pitch: 0,
  hospitality: 0,
  facilities: 0,
  staff_fitness: 0,
  staff_gkp: 0,
  staff_dfc: 0,
  staff_mid: 0,
  staff_att: 0,
  staff_scouts: 0,
  color_primary: 'Black',
  color_secondary: 'Red',
  bank_bal: 0,
  league: 'unmanaged',
  fan_happiness: 1,
  fanbase: 10000
)

countries = ['England', 'England', 'England', 'England', 'Scotland', 'Wales', 'NI', 'RoI', 'Brazil', 'Argentina', 'Spain', 'France', 'Germany', 'Poland', 'Portugal', 'USA', 'Belgium', 'Mexico', 'Uruguay','Brazil', 'England', 'Mexico', 'Germany', 'Italy', 'Spain', 'France', 'Argentina', 'Netherlands', 'Portugal', 'Belgium', 'Uruguay', 'Colombia', 'Croatia', 'Sweden', 'Switzerland', 'Poland', 'Denmark', 'Chile', 'Austria', 'Turkey', 'Russia', 'Japan', 'South Korea', 'Australia']
position_detail = ['c', 'c', 'c', 'l', 'r']
blend = [1,2,3,4,5,6,7,8,9]

100.times do
    Player.create(
      name: Faker::Name.last_name,
      age: random_number(18, 35),
      nationality: countries.sample,
      position: 'gkp',
      passing: random_number(3, 8),
      control: random_number(3, 8),
      tackling: random_number(3, 8),
      running: random_number(3, 5),
      shooting: random_number(3, 8),
      dribbling: random_number(3, 5),
      defensive_heading: random_number(3, 5),
      offensive_heading: random_number(3, 8),
      flair: random_number(3, 5),
      strength: random_number(3, 8),
      creativity: random_number(3, 5),
      fitness: 100,
      contract: random_number(3, 24),
      consistency: random_number(1, 20),
      loyalty: random_number(1, 50),
      blend: blend.sample,
      star: random_number(10, 30),
      club_id: 242,
      player_position_detail: 'p',
      potential_passing: random_number(8, 15),
      potential_control: random_number(8, 15),
      potential_tackling: random_number(8, 15),
      potential_running: random_number(5, 12),
      potential_shooting: random_number(8, 15),
      potential_dribbling: random_number(5, 12),
      potential_defensive_heading: random_number(5, 12),
      potential_offensive_heading: random_number(8, 15),
      potential_flair: random_number(5, 12),
      potential_strength: random_number(8, 15),
      potential_creativity: random_number(5, 12)
    )
  end

200.times do
    Player.create(
      name: Faker::Name.last_name,
      age: random_number(18, 35),
      nationality: countries.sample,
      position: 'dfc',
      passing: random_number(3, 5),
      control: random_number(3, 8),
      tackling: random_number(3, 8),
      running: random_number(3, 8),
      shooting: random_number(3, 5),
      dribbling: random_number(3, 5),
      defensive_heading: random_number(3, 8),
      offensive_heading: random_number(3, 5),
      flair: random_number(3, 5),
      strength: random_number(3, 8),
      creativity: random_number(3, 8),
      fitness: 100,
      contract: random_number(3, 24),
      consistency: random_number(1, 20),
      loyalty: random_number(1, 50),
      blend: blend.sample,
      star: random_number(10, 30),
      club_id: 242,
      player_position_detail: position_detail.sample,
      potential_passing: random_number(5, 12),
      potential_control: random_number(8, 15),
      potential_tackling: random_number(8, 15),
      potential_running: random_number(8, 15),
      potential_shooting: random_number(5, 12),
      potential_dribbling: random_number(5, 12),
      potential_defensive_heading: random_number(8, 15),
      potential_offensive_heading: random_number(5, 12),
      potential_flair: random_number(5, 12),
      potential_strength: random_number(8, 15),
      potential_creativity: random_number(8, 15)
    )
  end

200.times do
    Player.create(
      name: Faker::Name.last_name,
      age: random_number(18, 35),
      nationality: countries.sample,
      position: 'mid',
      passing: random_number(3, 8),
      control: random_number(3, 8),
      tackling: random_number(3, 5),
      running: random_number(3, 5),
      shooting: random_number(3, 8),
      dribbling: random_number(3, 8),
      defensive_heading: random_number(3, 5),
      offensive_heading: random_number(3, 5),
      flair: random_number(3, 8),
      strength: random_number(3, 5),
      creativity: random_number(3, 8),
      fitness: 100,
      contract: random_number(3, 24),
      consistency: random_number(1, 20),
      loyalty: random_number(1, 50),
      blend: blend.sample,
      star: random_number(10, 30),
      club_id: 242,
      player_position_detail: position_detail.sample,
      potential_passing: random_number(8, 15),
      potential_control: random_number(8, 15),
      potential_tackling: random_number(5, 12),
      potential_running: random_number(5, 12),
      potential_shooting: random_number(8, 15),
      potential_dribbling: random_number(8, 15),
      potential_defensive_heading: random_number(5, 12),
      potential_offensive_heading: random_number(5, 12),
      potential_flair: random_number(8, 15),
      potential_strength: random_number(5, 12),
      potential_creativity: random_number(8, 15)
    )
  end

200.times do
    Player.create(
      name: Faker::Name.last_name,
      age: random_number(18, 35),
      nationality: countries.sample,
      position: 'att',
      passing: random_number(3, 5),
      control: random_number(6, 9),
      tackling: random_number(3, 5),
      running: random_number(3, 8),
      shooting: random_number(3, 8),
      dribbling: random_number(3, 8),
      defensive_heading: random_number(3, 5),
      offensive_heading: random_number(3, 8),
      flair: random_number(3, 8),
      strength: random_number(3, 5),
      creativity: random_number(3, 5),
      fitness: 100,
      contract: random_number(3, 24),
      consistency: random_number(1, 20),
      loyalty: random_number(1, 50),
      blend: blend.sample,
      star: random_number(10, 30),
      club_id: 242,
      player_position_detail: position_detail.sample,
      potential_passing: random_number(5, 12),
      potential_control: random_number(8, 15),
      potential_tackling: random_number(5, 12),
      potential_running: random_number(8, 15),
      potential_shooting: random_number(8, 15),
      potential_dribbling: random_number(8, 15),
      potential_defensive_heading: random_number(5, 12),
      potential_offensive_heading: random_number(8, 15),
      potential_flair: random_number(8, 15),
      potential_strength: random_number(5, 12),
      potential_creativity: random_number(5, 12)
    )
  end
