templates = [
  { category: 'match_general', content: "{team} applies pressure in the midfield, but fails to find a way through the opponent's defense." },
  { category: 'match_general', content: "A well-executed counter-attack by {team}, but the final shot lacks accuracy and sails wide." },
  { category: 'match_general', content: "{team} launches a long-range effort, but the goalkeeper makes an excellent save to deny them." },
  { category: 'match_general', content: "{team} attempts a clever through ball, but the offside flag is raised." },
  { category: 'match_general', content: "The ball dances tantalizingly close to the goal line, but {team} fails to apply the finishing touch." },
  { category: 'match_general', content: "{team} launches a quick counter-attack, but their final pass is intercepted by the opposition's midfielder." },
  { category: 'match_general', content: "A well-timed tackle by the defender prevents {team} from getting a clear shot at goal." },
  { category: 'match_general', content: "{team}'s attacker finds themselves in a one-on-one situation, but the goalkeeper comes out on top with a remarkable save." },
  { category: 'match_general', content: "A clever set-piece routine by {team}, but the resulting shot is blocked by a wall of defenders." },
  { category: 'match_general', content: "{team} dominates possession, but struggles to create clear-cut opportunities in the final third." },
  { category: 'match_general', content: "{team} displays intricate passing in the box, but the shot is blocked by a desperate sliding tackle." },
  { category: 'match_chance', content: "{team} have a chance but its off target" },
  { category: 'match_chance', content: "{team} have a chance but they sky it, rubbish!" },
  { category: 'match_chance_tar', content: "{team} have a chance but the keeper saves" },
  { category: 'match_chance_tar', content: "chance for {team} but its blocked by a defender" },
  { category: 'match_goal', content: "Great play by {team} as a great challenge in midfield allows {assister} to create a chance for {scorer}. He hits the shot well and it goes in for a goal. Great strike!" },
  { category: 'match_goal', content: "A wonderful long pass from the left hand side pass by {assister} creates a chance for {scorer} who buries it. Goal for {team}" },
  { category: 'match_goal', content: "{assister} beats two players before slotting the ball to {scorer} who hits it first time. The ball flies into the net, leaving the goalkeeper helpless and the crowd roaring with delight. Goal for {team}" },
  { category: 'match_goal', content: "{team} are having a good spell now. After great play from {assister}, {scorer} hits a thunderous strike that finds the back of the net, sending shockwaves through the stadium." },
  { category: 'match_goal', content: "With precision and finesse, {scorer} slotted the ball past the diving goalkeeper. Assist by {assister} - {team} celebrate wildly." },
  { category: 'match_goal', content: "{team} free kick after {assister} is tripped 23 yards out. {scorer} hits a textbook finish, as the forward calmly placed the ball beyond the goalkeeper's reach. {assister} and {scorer} celebrate with the fans." },
  { category: 'match_goal', content: "{assister} and {scorer} play a 1-2 before {scorer} hits a booming shot that the goalkeeper can only watch in despair as the ball sails over his outstretched arms and into the top corner." },
  { category: 'match_goal', content: "An audacious chip over the goalkeeper left everyone in awe of the {scorer}'s skill and creativity. Goal to {team}, Assist {assister}. {scorer} taunts the opposition fans!" },
  { category: 'match_goal', content: "Goal {team}! A blistering shot from outside the box left the goalkeeper rooted to the spot. {scorer} hit it after a lovely dinked ball over the top from {assister}." },
  { category: 'match_goal', content: "Free kick on the edge of the area after a chop on {assister}. {scorer} takes it and the ball ricochetes off the post and into the net, sending the {team} fans into a frenzy." },
  { category: 'match_goal', content: "A corner into the box is flicked on by {assister} to {scorer} who perfectly executes a header that soars into the top corner, leaving the goalkeeper grasping at thin air and {team} celebrating." },
  { category: 'match_goal', content: "Penalty {team} - {assister} was fouled in the box but went down easily. VAR checked it but gave the spot kick for {team}. {scorer} takes it and the ball kisses the inside of the post before finding the back of the net, sparking wild celebrations." },
  { category: 'match_goal', content: "A mazy run by {assister} results in his shot from the edge of the area. The keeper saves it but it falls to {scorer} who hits a powerful volley that flies past the outstretched arms of the goalkeeper, announcing the striker's dominance in this game. Goal {team}." },
  { category: 'match_goal', content: "{team}s {assister} picks the ball up from the keeper and hits it long to {scorer} who shoots. The ball deflects off a defender before looping over the goalkeeper, leaving him stranded." },
  { category: 'match_goal', content: "A curling free-kick bent around the wall and nestles into the bottom corner, leaving the goalkeeper rooted to the spot. Goal for {team}. {scorer} is credited with it after {assister} was fouled." },
  { category: 'match_goal', content: "{assister} is playing well for {team}. He hits a shot from range that is blocked but {scorer} pounces on the loose ball and smashes it into the net, leaving the goalkeeper with no chance." },
  { category: 'match_goal', content: "{assister} hits a low corner into the box for {team}. {scorer} executes a perfectly timed flick of the heel to guide the ball into the net, leaving everyone in disbelief." },
  { category: 'match_goal', content: "A scorching shot by {scorer} from distance left the goalkeeper beaten and the {team} crowd in awe. {scorer} was put in on goal by {assister}." },
  { category: 'match_goal', content: "Fortunate goal for {team}. The shot from {scorer} took a wicked deflection, wrong-footing the goalkeeper and finding the back of the net. {assister} set the effort up." },
  { category: 'match_general', content: "{team} launches a long throw-in into the box, but the defense clears it away." },
  { category: 'match_general', content: "A well-timed sliding tackle by the defender prevents {team} from getting a shot off inside the penalty area." },
  { category: 'match_general', content: "{team} creates space with quick one-touch passing, but their shot is deflected out for a corner that comes to nothing." },
  { category: 'match_general', content: "{team} orchestrates a quick counter-attack, but the final shot lacks power and is easily gathered by the goalkeeper." },
  { category: 'match_general', content: "{team} shows great determination in the build-up, but their shot is blocked by a last-ditch tackle from the opposition's defender." },
  { category: 'match_chance_tar', content: "In a nail-biting match, {team} missed a golden opportunity to score, leaving {player} frustrated." },
  { category: 'match_chance_tar', content: "{player} had a perfect chance to score, but the ball flew just inches wide of the net, disappointing {team}." },
  { category: 'match_chance', content: "A well-placed pass went astray, denying {team} a scoring opportunity, much to the disappointment of {player}." },
  { category: 'match_chance', content: "{player} made a fantastic run towards the goal, but their shot hit the post, leaving {team} in disbelief." },
  { category: 'match_chance', content: "With an open goal in sight, {player} mishit the ball, causing {team} to rue their missed chance." },
  { category: 'match_chance', content: "A miscommunication between {player} and their teammate led to a missed scoring opportunity for {team}." },
  { category: 'match_chance', content: "{player} attempted a daring overhead kick, only for the ball to sail over the crossbar, much to {team}'s dismay." },
  { category: 'match_chance', content: "In a crucial moment, {player} failed to control a long pass, squandering {team}'s chance to score." },
  { category: 'match_chance_tar', content: "{player}'s shot was blocked by an exceptional save from the opposing goalkeeper, denying {team} a goal." },
  { category: 'match_general', content: "{team} applies pressure in the midfield, but fails to find a way through the opponent's defense." },
  { category: 'match_general', content: "A well-executed counter-attack by {team}, but the final shot lacks accuracy and sails wide." },
  { category: 'match_general', content: "{team} launches a long-range effort, but the goalkeeper makes an excellent save to deny them." },
  { category: 'match_general', content: "{team} attempts a clever through ball, but the offside flag is raised." },
  { category: 'match_general', content: "The ball dances tantalizingly close to the goal line, but {team} fails to apply the finishing touch." },
  { category: 'match_general', content: "{team} launches a quick counter-attack, but their final pass is intercepted by the opposition's midfielder." },
  { category: 'match_general', content: "A well-timed tackle by the defender prevents {team} from getting a clear shot at goal." },
  { category: 'match_general', content: "{team}'s attacker finds themselves in a one-on-one situation, but the goalkeeper comes out on top with a remarkable save." },
  { category: 'match_general', content: "A clever set-piece routine by {team}, but the resulting shot is blocked by a wall of defenders." },
  { category: 'match_general', content: "{team} dominates possession, but struggles to create clear-cut opportunities in the final third." },
  { category: 'match_general', content: "{team} displays intricate passing in the box, but the shot is blocked by a desperate sliding tackle." },
  { category: 'match_chance', content: "{team} built up a promising attack, but {player} slipped at the crucial moment, wasting a scoring opportunity." },
  { category: 'match_chance', content: "A last-minute tackle by the opponent denied {player} a clear shot at goal, leaving {team} frustrated." },
  { category: 'match_chance', content: "{player} attempted a powerful shot from outside the box, but it sailed just inches over the crossbar, disappointing {team}." },
  { category: 'match_chance', content: "With the goal at their mercy, {player} hesitated for a split second, allowing the defender to clear the ball, much to {team}'s frustration." },
  { category: 'match_chance', content: "{player} made a brilliant run down the wing but failed to deliver a precise cross, wasting a chance for {team}." },
  { category: 'match_chance', content: "A mistimed header from {player} meant that the ball went wide of the target, leaving {team} to rue their missed opportunity." },
  { category: 'match_chance', content: "{team} won a free-kick in a dangerous position, but {player}'s shot went straight into the wall, failing to trouble the opposing goalkeeper." },
  { category: 'match_chance', content: "{player} found themselves one-on-one with the goalkeeper but failed to find the back of the net, disappointing {team}." },
  { category: 'match_chance', content: "{team} launched a quick counter-attack, but {player} mistimed their pass, squandering a potential goal-scoring opportunity." },
  { category: 'match_chance', content: "{player} attempted a spectacular bicycle kick, but the ball sailed just wide of the goal, much to {team}'s frustration." },
  { category: 'match_chance_tar', content: "{team} won a penalty, but {player}'s shot was saved by the goalkeeper, leaving {team} to lament their missed chance." },
  { category: 'match_chance', content: "A moment of hesitation from {player} allowed the defender to intercept the ball, denying {team} a clear scoring opportunity." },
  { category: 'match_chance_tar', content: "{player} had a clear path to the goal, but their shot lacked power, making it an easy save for the opposing goalkeeper, much to {team}'s disappointment." },
  { category: 'match_chance', content: "{team} launched a swift counter-attack, but {player} failed to make the right decision, leading to a missed chance." },
  { category: 'match_chance', content: '{player} attempted a long-range shot, but it sailed high over the crossbar, leaving {team} frustrated.' },
  { category: 'match_chance', content: 'A brilliant through ball from {player} went unnoticed by their teammate, wasting a potential goal-scoring opportunity for {team}.' },
  { category: 'match_chance', content: "{team} won a corner kick, but {player}'s delivery failed to find a teammate, squandering a chance to score." },
  { category: 'match_chance_tar', content: 	'{player} found themselves in a one-on-one situation against the goalkeeper, but their shot was saved, leaving {team} to regret their missed chance.' },
  { category: 'match_chance', content: 	"A misplaced pass from {player} halted {team}'s attacking move, denying them a scoring opportunity." },
  { category: 'match_chance', content: 	"{player} attempted an audacious chip shot, but it lacked accuracy, sailing over the crossbar, much to {team}'s frustration." },
  { category: 'match_chance', content: 	'{team} created a promising counter-attack, but {player} lost control of the ball, wasting a chance to score.' }
]

templates.each do |template|
  Template.create(
    commentary_type: template[:category],
    text: template[:content]
  )
end
