services:
  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ftw_postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - my_network
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - .:/app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_HOST=db
      - REDIS_URL=redis://redis:6379
      - DOCKER_LOGS=true
    depends_on:
      - db
    networks:
      - my_network

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    restart: always
    networks:
      - my_network

  sidekiq:
    build:
      context: .
      dockerfile: docker/sidekiq/Dockerfile
    restart: always
    depends_on:
      - redis
    ports:
      - "6380:6379"
    networks:
      - my_network
    environment:
      REDIS_URL: redis://redis:6379

networks:
  my_network:

volumes:
  ftw_postgres_data: