hashfix = [
  { week_number: 1, home: 1, away: 2, comp: 'Premier League' },
  { week_number: 1, home: 3, away: 4, comp: 'Premier League' },
  { week_number: 1, home: 5, away: 6, comp: 'Premier League' },
  { week_number: 1, home: 7, away: 8, comp: 'Premier League' },
  { week_number: 1, home: 9, away: 10, comp: 'Premier League' },
  { week_number: 1, home: 16, away: 11, comp: 'Premier League' },
  { week_number: 1, home: 12, away: 13, comp: 'Premier League' },
  { week_number: 1, home: 14, away: 15, comp: 'Premier League' },
  { week_number: 1, home: 17, away: 18, comp: 'Premier League' },
  { week_number: 1, home: 19, away: 20, comp: 'Premier League' },
  { week_number: 2, home: 4, away: 1, comp: 'Premier League' },
  { week_number: 2, home: 6, away: 2, comp: 'Premier League' },
  { week_number: 2, home: 8, away: 3, comp: 'Premier League' },
  { week_number: 2, home: 10, away: 5, comp: 'Premier League' },
  { week_number: 2, home: 11, away: 7, comp: 'Premier League' },
  { week_number: 2, home: 13, away: 9, comp: 'Premier League' },
  { week_number: 2, home: 15, away: 16, comp: 'Premier League' },
  { week_number: 2, home: 18, away: 12, comp: 'Premier League' },
  { week_number: 2, home: 20, away: 14, comp: 'Premier League' },
  { week_number: 2, home: 19, away: 17, comp: 'Premier League' },
  { week_number: 3, home: 1, away: 6, comp: 'Premier League' },
  { week_number: 3, home: 4, away: 8, comp: 'Premier League' },
  { week_number: 3, home: 2, away: 10, comp: 'Premier League' },
  { week_number: 3, home: 3, away: 11, comp: 'Premier League' },
  { week_number: 3, home: 5, away: 13, comp: 'Premier League' },
  { week_number: 3, home: 7, away: 15, comp: 'Premier League' },
  { week_number: 3, home: 9, away: 18, comp: 'Premier League' },
  { week_number: 3, home: 16, away: 20, comp: 'Premier League' },
  { week_number: 3, home: 12, away: 19, comp: 'Premier League' },
  { week_number: 3, home: 14, away: 17, comp: 'Premier League' },
  { week_number: 4, home: 8, away: 1, comp: 'Premier League' },
  { week_number: 4, home: 10, away: 6, comp: 'Premier League' },
  { week_number: 4, home: 11, away: 4, comp: 'Premier League' },
  { week_number: 4, home: 13, away: 2, comp: 'Premier League' },
  { week_number: 4, home: 15, away: 3, comp: 'Premier League' },
  { week_number: 4, home: 18, away: 5, comp: 'Premier League' },
  { week_number: 4, home: 20, away: 7, comp: 'Premier League' },
  { week_number: 4, home: 19, away: 9, comp: 'Premier League' },
  { week_number: 4, home: 17, away: 16, comp: 'Premier League' },
  { week_number: 4, home: 14, away: 12, comp: 'Premier League' },
  { week_number: 5, home: 1, away: 10, comp: 'Premier League' },
  { week_number: 5, home: 8, away: 11, comp: 'Premier League' },
  { week_number: 5, home: 6, away: 13, comp: 'Premier League' },
  { week_number: 5, home: 4, away: 15, comp: 'Premier League' },
  { week_number: 5, home: 2, away: 18, comp: 'Premier League' },
  { week_number: 5, home: 3, away: 20, comp: 'Premier League' },
  { week_number: 5, home: 5, away: 19, comp: 'Premier League' },
  { week_number: 5, home: 7, away: 17, comp: 'Premier League' },
  { week_number: 5, home: 9, away: 14, comp: 'Premier League' },
  { week_number: 5, home: 16, away: 12, comp: 'Premier League' },
  { week_number: 6, home: 11, away: 1, comp: 'Premier League' },
  { week_number: 6, home: 13, away: 10, comp: 'Premier League' },
  { week_number: 6, home: 15, away: 8, comp: 'Premier League' },
  { week_number: 6, home: 18, away: 6, comp: 'Premier League' },
  { week_number: 6, home: 20, away: 4, comp: 'Premier League' },
  { week_number: 6, home: 19, away: 2, comp: 'Premier League' },
  { week_number: 6, home: 17, away: 3, comp: 'Premier League' },
  { week_number: 6, home: 14, away: 5, comp: 'Premier League' },
  { week_number: 6, home: 12, away: 7, comp: 'Premier League' },
  { week_number: 6, home: 16, away: 9, comp: 'Premier League' },
  { week_number: 7, home: 1, away: 13, comp: 'Premier League' },
  { week_number: 7, home: 11, away: 15, comp: 'Premier League' },
  { week_number: 7, home: 10, away: 18, comp: 'Premier League' },
  { week_number: 7, home: 8, away: 20, comp: 'Premier League' },
  { week_number: 7, home: 6, away: 19, comp: 'Premier League' },
  { week_number: 7, home: 4, away: 17, comp: 'Premier League' },
  { week_number: 7, home: 2, away: 14, comp: 'Premier League' },
  { week_number: 7, home: 3, away: 12, comp: 'Premier League' },
  { week_number: 7, home: 5, away: 16, comp: 'Premier League' },
  { week_number: 7, home: 7, away: 9, comp: 'Premier League' },
  { week_number: 8, home: 15, away: 1, comp: 'Premier League' },
  { week_number: 8, home: 18, away: 13, comp: 'Premier League' },
  { week_number: 8, home: 20, away: 11, comp: 'Premier League' },
  { week_number: 8, home: 19, away: 10, comp: 'Premier League' },
  { week_number: 8, home: 17, away: 8, comp: 'Premier League' },
  { week_number: 8, home: 14, away: 6, comp: 'Premier League' },
  { week_number: 8, home: 12, away: 4, comp: 'Premier League' },
  { week_number: 8, home: 16, away: 2, comp: 'Premier League' },
  { week_number: 8, home: 9, away: 3, comp: 'Premier League' },
  { week_number: 8, home: 7, away: 5, comp: 'Premier League' },
  { week_number: 9, home: 1, away: 18, comp: 'Premier League' },
  { week_number: 9, home: 15, away: 20, comp: 'Premier League' },
  { week_number: 9, home: 13, away: 19, comp: 'Premier League' },
  { week_number: 9, home: 11, away: 17, comp: 'Premier League' },
  { week_number: 9, home: 10, away: 14, comp: 'Premier League' },
  { week_number: 9, home: 8, away: 12, comp: 'Premier League' },
  { week_number: 9, home: 6, away: 16, comp: 'Premier League' },
  { week_number: 9, home: 4, away: 9, comp: 'Premier League' },
  { week_number: 9, home: 2, away: 7, comp: 'Premier League' },
  { week_number: 9, home: 3, away: 5, comp: 'Premier League' },
  { week_number: 10, home: 20, away: 1, comp: 'Premier League' },
  { week_number: 10, home: 19, away: 18, comp: 'Premier League' },
  { week_number: 10, home: 17, away: 15, comp: 'Premier League' },
  { week_number: 10, home: 14, away: 13, comp: 'Premier League' },
  { week_number: 10, home: 12, away: 11, comp: 'Premier League' },
  { week_number: 10, home: 16, away: 10, comp: 'Premier League' },
  { week_number: 10, home: 9, away: 8, comp: 'Premier League' },
  { week_number: 10, home: 7, away: 6, comp: 'Premier League' },
  { week_number: 10, home: 5, away: 4, comp: 'Premier League' },
  { week_number: 10, home: 3, away: 2, comp: 'Premier League' },
  { week_number: 11, home: 1, away: 19, comp: 'Premier League' },
  { week_number: 11, home: 20, away: 17, comp: 'Premier League' },
  { week_number: 11, home: 18, away: 14, comp: 'Premier League' },
  { week_number: 11, home: 15, away: 12, comp: 'Premier League' },
  { week_number: 11, home: 13, away: 16, comp: 'Premier League' },
  { week_number: 11, home: 11, away: 9, comp: 'Premier League' },
  { week_number: 11, home: 10, away: 7, comp: 'Premier League' },
  { week_number: 11, home: 8, away: 5, comp: 'Premier League' },
  { week_number: 11, home: 6, away: 3, comp: 'Premier League' },
  { week_number: 11, home: 4, away: 2, comp: 'Premier League' },
  { week_number: 12, home: 17, away: 1, comp: 'Premier League' },
  { week_number: 12, home: 14, away: 19, comp: 'Premier League' },
  { week_number: 12, home: 12, away: 20, comp: 'Premier League' },
  { week_number: 12, home: 16, away: 18, comp: 'Premier League' },
  { week_number: 12, home: 9, away: 15, comp: 'Premier League' },
  { week_number: 12, home: 7, away: 13, comp: 'Premier League' },
  { week_number: 12, home: 5, away: 11, comp: 'Premier League' },
  { week_number: 12, home: 3, away: 10, comp: 'Premier League' },
  { week_number: 12, home: 2, away: 8, comp: 'Premier League' },
  { week_number: 12, home: 4, away: 6, comp: 'Premier League' },
  { week_number: 13, home: 1, away: 14, comp: 'Premier League' },
  { week_number: 13, home: 17, away: 12, comp: 'Premier League' },
  { week_number: 13, home: 19, away: 16, comp: 'Premier League' },
  { week_number: 13, home: 20, away: 9, comp: 'Premier League' },
  { week_number: 13, home: 18, away: 7, comp: 'Premier League' },
  { week_number: 13, home: 15, away: 5, comp: 'Premier League' },
  { week_number: 13, home: 13, away: 3, comp: 'Premier League' },
  { week_number: 13, home: 11, away: 2, comp: 'Premier League' },
  { week_number: 13, home: 10, away: 4, comp: 'Premier League' },
  { week_number: 13, home: 8, away: 6, comp: 'Premier League' },
  { week_number: 14, home: 12, away: 1, comp: 'Premier League' },
  { week_number: 14, home: 16, away: 14, comp: 'Premier League' },
  { week_number: 14, home: 9, away: 17, comp: 'Premier League' },
  { week_number: 14, home: 7, away: 19, comp: 'Premier League' },
  { week_number: 14, home: 5, away: 20, comp: 'Premier League' },
  { week_number: 14, home: 3, away: 18, comp: 'Premier League' },
  { week_number: 14, home: 2, away: 15, comp: 'Premier League' },
  { week_number: 14, home: 4, away: 13, comp: 'Premier League' },
  { week_number: 14, home: 6, away: 11, comp: 'Premier League' },
  { week_number: 14, home: 8, away: 10, comp: 'Premier League' },
  { week_number: 15, home: 1, away: 16, comp: 'Premier League' },
  { week_number: 15, home: 12, away: 9, comp: 'Premier League' },
  { week_number: 15, home: 14, away: 7, comp: 'Premier League' },
  { week_number: 15, home: 17, away: 5, comp: 'Premier League' },
  { week_number: 15, home: 19, away: 3, comp: 'Premier League' },
  { week_number: 15, home: 20, away: 2, comp: 'Premier League' },
  { week_number: 15, home: 18, away: 4, comp: 'Premier League' },
  { week_number: 15, home: 15, away: 6, comp: 'Premier League' },
  { week_number: 15, home: 13, away: 8, comp: 'Premier League' },
  { week_number: 15, home: 11, away: 10, comp: 'Premier League' },
  { week_number: 16, home: 9, away: 1, comp: 'Premier League' },
  { week_number: 16, home: 7, away: 16, comp: 'Premier League' },
  { week_number: 16, home: 5, away: 12, comp: 'Premier League' },
  { week_number: 16, home: 3, away: 14, comp: 'Premier League' },
  { week_number: 16, home: 2, away: 17, comp: 'Premier League' },
  { week_number: 16, home: 4, away: 19, comp: 'Premier League' },
  { week_number: 16, home: 6, away: 20, comp: 'Premier League' },
  { week_number: 16, home: 8, away: 18, comp: 'Premier League' },
  { week_number: 16, home: 10, away: 15, comp: 'Premier League' },
  { week_number: 16, home: 11, away: 13, comp: 'Premier League' },
  { week_number: 17, home: 1, away: 7, comp: 'Premier League' },
  { week_number: 17, home: 9, away: 5, comp: 'Premier League' },
  { week_number: 17, home: 16, away: 3, comp: 'Premier League' },
  { week_number: 17, home: 12, away: 2, comp: 'Premier League' },
  { week_number: 17, home: 14, away: 4, comp: 'Premier League' },
  { week_number: 17, home: 17, away: 6, comp: 'Premier League' },
  { week_number: 17, home: 19, away: 8, comp: 'Premier League' },
  { week_number: 17, home: 20, away: 10, comp: 'Premier League' },
  { week_number: 17, home: 18, away: 11, comp: 'Premier League' },
  { week_number: 17, home: 15, away: 13, comp: 'Premier League' },
  { week_number: 18, home: 5, away: 1, comp: 'Premier League' },
  { week_number: 18, home: 3, away: 7, comp: 'Premier League' },
  { week_number: 18, home: 2, away: 9, comp: 'Premier League' },
  { week_number: 18, home: 4, away: 16, comp: 'Premier League' },
  { week_number: 18, home: 6, away: 12, comp: 'Premier League' },
  { week_number: 18, home: 8, away: 14, comp: 'Premier League' },
  { week_number: 18, home: 10, away: 17, comp: 'Premier League' },
  { week_number: 18, home: 11, away: 19, comp: 'Premier League' },
  { week_number: 18, home: 13, away: 20, comp: 'Premier League' },
  { week_number: 18, home: 15, away: 18, comp: 'Premier League' },
  { week_number: 19, home: 1, away: 3, comp: 'Premier League' },
  { week_number: 19, home: 5, away: 2, comp: 'Premier League' },
  { week_number: 19, home: 7, away: 4, comp: 'Premier League' },
  { week_number: 19, home: 9, away: 6, comp: 'Premier League' },
  { week_number: 19, home: 16, away: 8, comp: 'Premier League' },
  { week_number: 19, home: 12, away: 10, comp: 'Premier League' },
  { week_number: 19, home: 14, away: 11, comp: 'Premier League' },
  { week_number: 19, home: 17, away: 13, comp: 'Premier League' },
  { week_number: 19, home: 19, away: 15, comp: 'Premier League' },
  { week_number: 19, home: 20, away: 18, comp: 'Premier League' },
  { week_number: 20, home: 2, away: 1, comp: 'Premier League' },
  { week_number: 20, home: 4, away: 3, comp: 'Premier League' },
  { week_number: 20, home: 6, away: 5, comp: 'Premier League' },
  { week_number: 20, home: 8, away: 7, comp: 'Premier League' },
  { week_number: 20, home: 10, away: 9, comp: 'Premier League' },
  { week_number: 20, home: 11, away: 16, comp: 'Premier League' },
  { week_number: 20, home: 13, away: 12, comp: 'Premier League' },
  { week_number: 20, home: 15, away: 14, comp: 'Premier League' },
  { week_number: 20, home: 18, away: 17, comp: 'Premier League' },
  { week_number: 20, home: 20, away: 19, comp: 'Premier League' },
  { week_number: 21, home: 1, away: 4, comp: 'Premier League' },
  { week_number: 21, home: 2, away: 6, comp: 'Premier League' },
  { week_number: 21, home: 3, away: 8, comp: 'Premier League' },
  { week_number: 21, home: 5, away: 10, comp: 'Premier League' },
  { week_number: 21, home: 7, away: 11, comp: 'Premier League' },
  { week_number: 21, home: 9, away: 13, comp: 'Premier League' },
  { week_number: 21, home: 16, away: 15, comp: 'Premier League' },
  { week_number: 21, home: 12, away: 18, comp: 'Premier League' },
  { week_number: 21, home: 14, away: 20, comp: 'Premier League' },
  { week_number: 21, home: 17, away: 19, comp: 'Premier League' },
  { week_number: 22, home: 6, away: 1, comp: 'Premier League' },
  { week_number: 22, home: 8, away: 4, comp: 'Premier League' },
  { week_number: 22, home: 10, away: 2, comp: 'Premier League' },
  { week_number: 22, home: 11, away: 3, comp: 'Premier League' },
  { week_number: 22, home: 13, away: 5, comp: 'Premier League' },
  { week_number: 22, home: 15, away: 7, comp: 'Premier League' },
  { week_number: 22, home: 18, away: 9, comp: 'Premier League' },
  { week_number: 22, home: 20, away: 16, comp: 'Premier League' },
  { week_number: 22, home: 19, away: 12, comp: 'Premier League' },
  { week_number: 22, home: 17, away: 14, comp: 'Premier League' },
  { week_number: 23, home: 1, away: 8, comp: 'Premier League' },
  { week_number: 23, home: 6, away: 10, comp: 'Premier League' },
  { week_number: 23, home: 4, away: 11, comp: 'Premier League' },
  { week_number: 23, home: 2, away: 13, comp: 'Premier League' },
  { week_number: 23, home: 3, away: 15, comp: 'Premier League' },
  { week_number: 23, home: 5, away: 18, comp: 'Premier League' },
  { week_number: 23, home: 7, away: 20, comp: 'Premier League' },
  { week_number: 23, home: 9, away: 19, comp: 'Premier League' },
  { week_number: 23, home: 16, away: 17, comp: 'Premier League' },
  { week_number: 23, home: 12, away: 14, comp: 'Premier League' },
  { week_number: 24, home: 10, away: 1, comp: 'Premier League' },
  { week_number: 24, home: 11, away: 8, comp: 'Premier League' },
  { week_number: 24, home: 13, away: 6, comp: 'Premier League' },
  { week_number: 24, home: 15, away: 4, comp: 'Premier League' },
  { week_number: 24, home: 18, away: 2, comp: 'Premier League' },
  { week_number: 24, home: 20, away: 3, comp: 'Premier League' },
  { week_number: 24, home: 19, away: 5, comp: 'Premier League' },
  { week_number: 24, home: 17, away: 7, comp: 'Premier League' },
  { week_number: 24, home: 14, away: 9, comp: 'Premier League' },
  { week_number: 24, home: 12, away: 16, comp: 'Premier League' },
  { week_number: 25, home: 1, away: 11, comp: 'Premier League' },
  { week_number: 25, home: 10, away: 13, comp: 'Premier League' },
  { week_number: 25, home: 8, away: 15, comp: 'Premier League' },
  { week_number: 25, home: 6, away: 18, comp: 'Premier League' },
  { week_number: 25, home: 4, away: 20, comp: 'Premier League' },
  { week_number: 25, home: 2, away: 19, comp: 'Premier League' },
  { week_number: 25, home: 3, away: 17, comp: 'Premier League' },
  { week_number: 25, home: 5, away: 14, comp: 'Premier League' },
  { week_number: 25, home: 7, away: 12, comp: 'Premier League' },
  { week_number: 25, home: 9, away: 16, comp: 'Premier League' },
  { week_number: 26, home: 13, away: 1, comp: 'Premier League' },
  { week_number: 26, home: 15, away: 11, comp: 'Premier League' },
  { week_number: 26, home: 18, away: 10, comp: 'Premier League' },
  { week_number: 26, home: 20, away: 8, comp: 'Premier League' },
  { week_number: 26, home: 19, away: 6, comp: 'Premier League' },
  { week_number: 26, home: 17, away: 4, comp: 'Premier League' },
  { week_number: 26, home: 14, away: 2, comp: 'Premier League' },
  { week_number: 26, home: 12, away: 3, comp: 'Premier League' },
  { week_number: 26, home: 16, away: 5, comp: 'Premier League' },
  { week_number: 26, home: 9, away: 7, comp: 'Premier League' },
  { week_number: 27, home: 1, away: 15, comp: 'Premier League' },
  { week_number: 27, home: 13, away: 18, comp: 'Premier League' },
  { week_number: 27, home: 11, away: 20, comp: 'Premier League' },
  { week_number: 27, home: 10, away: 19, comp: 'Premier League' },
  { week_number: 27, home: 8, away: 17, comp: 'Premier League' },
  { week_number: 27, home: 6, away: 14, comp: 'Premier League' },
  { week_number: 27, home: 4, away: 12, comp: 'Premier League' },
  { week_number: 27, home: 2, away: 16, comp: 'Premier League' },
  { week_number: 27, home: 3, away: 9, comp: 'Premier League' },
  { week_number: 27, home: 5, away: 7, comp: 'Premier League' },
  { week_number: 28, home: 18, away: 1, comp: 'Premier League' },
  { week_number: 28, home: 20, away: 15, comp: 'Premier League' },
  { week_number: 28, home: 19, away: 13, comp: 'Premier League' },
  { week_number: 28, home: 17, away: 11, comp: 'Premier League' },
  { week_number: 28, home: 14, away: 10, comp: 'Premier League' },
  { week_number: 28, home: 12, away: 8, comp: 'Premier League' },
  { week_number: 28, home: 16, away: 6, comp: 'Premier League' },
  { week_number: 28, home: 9, away: 4, comp: 'Premier League' },
  { week_number: 28, home: 7, away: 2, comp: 'Premier League' },
  { week_number: 28, home: 5, away: 3, comp: 'Premier League' },
  { week_number: 29, home: 1, away: 20, comp: 'Premier League' },
  { week_number: 29, home: 18, away: 19, comp: 'Premier League' },
  { week_number: 29, home: 15, away: 17, comp: 'Premier League' },
  { week_number: 29, home: 13, away: 14, comp: 'Premier League' },
  { week_number: 29, home: 11, away: 12, comp: 'Premier League' },
  { week_number: 29, home: 10, away: 16, comp: 'Premier League' },
  { week_number: 29, home: 8, away: 9, comp: 'Premier League' },
  { week_number: 29, home: 6, away: 7, comp: 'Premier League' },
  { week_number: 29, home: 4, away: 5, comp: 'Premier League' },
  { week_number: 29, home: 2, away: 3, comp: 'Premier League' },
  { week_number: 30, home: 19, away: 1, comp: 'Premier League' },
  { week_number: 30, home: 17, away: 20, comp: 'Premier League' },
  { week_number: 30, home: 14, away: 18, comp: 'Premier League' },
  { week_number: 30, home: 12, away: 15, comp: 'Premier League' },
  { week_number: 30, home: 16, away: 13, comp: 'Premier League' },
  { week_number: 30, home: 9, away: 11, comp: 'Premier League' },
  { week_number: 30, home: 7, away: 10, comp: 'Premier League' },
  { week_number: 30, home: 5, away: 8, comp: 'Premier League' },
  { week_number: 30, home: 3, away: 6, comp: 'Premier League' },
  { week_number: 30, home: 2, away: 4, comp: 'Premier League' },
  { week_number: 31, home: 1, away: 17, comp: 'Premier League' },
  { week_number: 31, home: 19, away: 14, comp: 'Premier League' },
  { week_number: 31, home: 20, away: 12, comp: 'Premier League' },
  { week_number: 31, home: 18, away: 16, comp: 'Premier League' },
  { week_number: 31, home: 15, away: 9, comp: 'Premier League' },
  { week_number: 31, home: 13, away: 7, comp: 'Premier League' },
  { week_number: 31, home: 11, away: 5, comp: 'Premier League' },
  { week_number: 31, home: 10, away: 3, comp: 'Premier League' },
  { week_number: 31, home: 8, away: 2, comp: 'Premier League' },
  { week_number: 31, home: 6, away: 4, comp: 'Premier League' },
  { week_number: 32, home: 14, away: 1, comp: 'Premier League' },
  { week_number: 32, home: 12, away: 17, comp: 'Premier League' },
  { week_number: 32, home: 16, away: 19, comp: 'Premier League' },
  { week_number: 32, home: 9, away: 20, comp: 'Premier League' },
  { week_number: 32, home: 7, away: 18, comp: 'Premier League' },
  { week_number: 32, home: 5, away: 15, comp: 'Premier League' },
  { week_number: 32, home: 3, away: 13, comp: 'Premier League' },
  { week_number: 32, home: 2, away: 11, comp: 'Premier League' },
  { week_number: 32, home: 4, away: 10, comp: 'Premier League' },
  { week_number: 32, home: 6, away: 8, comp: 'Premier League' },
  { week_number: 33, home: 1, away: 12, comp: 'Premier League' },
  { week_number: 33, home: 14, away: 16, comp: 'Premier League' },
  { week_number: 33, home: 17, away: 9, comp: 'Premier League' },
  { week_number: 33, home: 19, away: 7, comp: 'Premier League' },
  { week_number: 33, home: 20, away: 5, comp: 'Premier League' },
  { week_number: 33, home: 18, away: 3, comp: 'Premier League' },
  { week_number: 33, home: 15, away: 2, comp: 'Premier League' },
  { week_number: 33, home: 13, away: 4, comp: 'Premier League' },
  { week_number: 33, home: 11, away: 6, comp: 'Premier League' },
  { week_number: 33, home: 10, away: 8, comp: 'Premier League' },
  { week_number: 34, home: 16, away: 1, comp: 'Premier League' },
  { week_number: 34, home: 9, away: 12, comp: 'Premier League' },
  { week_number: 34, home: 7, away: 14, comp: 'Premier League' },
  { week_number: 34, home: 5, away: 17, comp: 'Premier League' },
  { week_number: 34, home: 3, away: 19, comp: 'Premier League' },
  { week_number: 34, home: 2, away: 20, comp: 'Premier League' },
  { week_number: 34, home: 4, away: 18, comp: 'Premier League' },
  { week_number: 34, home: 6, away: 15, comp: 'Premier League' },
  { week_number: 34, home: 8, away: 13, comp: 'Premier League' },
  { week_number: 34, home: 10, away: 11, comp: 'Premier League' },
  { week_number: 35, home: 1, away: 9, comp: 'Premier League' },
  { week_number: 35, home: 16, away: 7, comp: 'Premier League' },
  { week_number: 35, home: 12, away: 5, comp: 'Premier League' },
  { week_number: 35, home: 14, away: 3, comp: 'Premier League' },
  { week_number: 35, home: 17, away: 2, comp: 'Premier League' },
  { week_number: 35, home: 19, away: 4, comp: 'Premier League' },
  { week_number: 35, home: 20, away: 6, comp: 'Premier League' },
  { week_number: 35, home: 18, away: 8, comp: 'Premier League' },
  { week_number: 35, home: 15, away: 10, comp: 'Premier League' },
  { week_number: 35, home: 13, away: 11, comp: 'Premier League' },
  { week_number: 36, home: 7, away: 1, comp: 'Premier League' },
  { week_number: 36, home: 5, away: 9, comp: 'Premier League' },
  { week_number: 36, home: 3, away: 16, comp: 'Premier League' },
  { week_number: 36, home: 2, away: 12, comp: 'Premier League' },
  { week_number: 36, home: 4, away: 14, comp: 'Premier League' },
  { week_number: 36, home: 6, away: 17, comp: 'Premier League' },
  { week_number: 36, home: 8, away: 19, comp: 'Premier League' },
  { week_number: 36, home: 10, away: 20, comp: 'Premier League' },
  { week_number: 36, home: 11, away: 18, comp: 'Premier League' },
  { week_number: 36, home: 13, away: 15, comp: 'Premier League' },
  { week_number: 37, home: 1, away: 5, comp: 'Premier League' },
  { week_number: 37, home: 7, away: 3, comp: 'Premier League' },
  { week_number: 37, home: 9, away: 2, comp: 'Premier League' },
  { week_number: 37, home: 16, away: 4, comp: 'Premier League' },
  { week_number: 37, home: 12, away: 6, comp: 'Premier League' },
  { week_number: 37, home: 14, away: 8, comp: 'Premier League' },
  { week_number: 37, home: 17, away: 10, comp: 'Premier League' },
  { week_number: 37, home: 19, away: 11, comp: 'Premier League' },
  { week_number: 37, home: 20, away: 13, comp: 'Premier League' },
  { week_number: 37, home: 18, away: 15, comp: 'Premier League' },
  { week_number: 38, home: 3, away: 1, comp: 'Premier League' },
  { week_number: 38, home: 2, away: 5, comp: 'Premier League' },
  { week_number: 38, home: 4, away: 7, comp: 'Premier League' },
  { week_number: 38, home: 6, away: 9, comp: 'Premier League' },
  { week_number: 38, home: 8, away: 16, comp: 'Premier League' },
  { week_number: 38, home: 10, away: 12, comp: 'Premier League' },
  { week_number: 38, home: 11, away: 14, comp: 'Premier League' },
  { week_number: 38, home: 13, away: 17, comp: 'Premier League' },
  { week_number: 38, home: 15, away: 19, comp: 'Premier League' },
  { week_number: 38, home: 18, away: 20, comp: 'Premier League' },
  { week_number: 1, home: 21, away: 22, comp: 'Championship' },
  { week_number: 1, home: 23, away: 24, comp: 'Championship' },
  { week_number: 1, home: 25, away: 26, comp: 'Championship' },
  { week_number: 1, home: 27, away: 28, comp: 'Championship' },
  { week_number: 1, home: 29, away: 30, comp: 'Championship' },
  { week_number: 1, home: 36, away: 31, comp: 'Championship' },
  { week_number: 1, home: 32, away: 33, comp: 'Championship' },
  { week_number: 1, home: 34, away: 35, comp: 'Championship' },
  { week_number: 1, home: 37, away: 38, comp: 'Championship' },
  { week_number: 1, home: 39, away: 40, comp: 'Championship' },
  { week_number: 2, home: 24, away: 21, comp: 'Championship' },
  { week_number: 2, home: 26, away: 22, comp: 'Championship' },
  { week_number: 2, home: 28, away: 23, comp: 'Championship' },
  { week_number: 2, home: 30, away: 25, comp: 'Championship' },
  { week_number: 2, home: 31, away: 27, comp: 'Championship' },
  { week_number: 2, home: 33, away: 29, comp: 'Championship' },
  { week_number: 2, home: 35, away: 36, comp: 'Championship' },
  { week_number: 2, home: 38, away: 32, comp: 'Championship' },
  { week_number: 2, home: 40, away: 34, comp: 'Championship' },
  { week_number: 2, home: 39, away: 37, comp: 'Championship' },
  { week_number: 3, home: 21, away: 26, comp: 'Championship' },
  { week_number: 3, home: 24, away: 28, comp: 'Championship' },
  { week_number: 3, home: 22, away: 30, comp: 'Championship' },
  { week_number: 3, home: 23, away: 31, comp: 'Championship' },
  { week_number: 3, home: 25, away: 33, comp: 'Championship' },
  { week_number: 3, home: 27, away: 35, comp: 'Championship' },
  { week_number: 3, home: 29, away: 38, comp: 'Championship' },
  { week_number: 3, home: 36, away: 40, comp: 'Championship' },
  { week_number: 3, home: 32, away: 39, comp: 'Championship' },
  { week_number: 3, home: 34, away: 37, comp: 'Championship' },
  { week_number: 4, home: 28, away: 21, comp: 'Championship' },
  { week_number: 4, home: 30, away: 26, comp: 'Championship' },
  { week_number: 4, home: 31, away: 24, comp: 'Championship' },
  { week_number: 4, home: 33, away: 22, comp: 'Championship' },
  { week_number: 4, home: 35, away: 23, comp: 'Championship' },
  { week_number: 4, home: 38, away: 25, comp: 'Championship' },
  { week_number: 4, home: 40, away: 27, comp: 'Championship' },
  { week_number: 4, home: 39, away: 29, comp: 'Championship' },
  { week_number: 4, home: 37, away: 36, comp: 'Championship' },
  { week_number: 4, home: 34, away: 32, comp: 'Championship' },
  { week_number: 5, home: 21, away: 30, comp: 'Championship' },
  { week_number: 5, home: 28, away: 31, comp: 'Championship' },
  { week_number: 5, home: 26, away: 33, comp: 'Championship' },
  { week_number: 5, home: 24, away: 35, comp: 'Championship' },
  { week_number: 5, home: 22, away: 38, comp: 'Championship' },
  { week_number: 5, home: 23, away: 40, comp: 'Championship' },
  { week_number: 5, home: 25, away: 39, comp: 'Championship' },
  { week_number: 5, home: 27, away: 37, comp: 'Championship' },
  { week_number: 5, home: 29, away: 34, comp: 'Championship' },
  { week_number: 5, home: 36, away: 32, comp: 'Championship' },
  { week_number: 6, home: 31, away: 21, comp: 'Championship' },
  { week_number: 6, home: 33, away: 30, comp: 'Championship' },
  { week_number: 6, home: 35, away: 28, comp: 'Championship' },
  { week_number: 6, home: 38, away: 26, comp: 'Championship' },
  { week_number: 6, home: 40, away: 24, comp: 'Championship' },
  { week_number: 6, home: 39, away: 22, comp: 'Championship' },
  { week_number: 6, home: 37, away: 23, comp: 'Championship' },
  { week_number: 6, home: 34, away: 25, comp: 'Championship' },
  { week_number: 6, home: 32, away: 27, comp: 'Championship' },
  { week_number: 6, home: 36, away: 29, comp: 'Championship' },
  { week_number: 7, home: 21, away: 33, comp: 'Championship' },
  { week_number: 7, home: 31, away: 35, comp: 'Championship' },
  { week_number: 7, home: 30, away: 38, comp: 'Championship' },
  { week_number: 7, home: 28, away: 40, comp: 'Championship' },
  { week_number: 7, home: 26, away: 39, comp: 'Championship' },
  { week_number: 7, home: 24, away: 37, comp: 'Championship' },
  { week_number: 7, home: 22, away: 34, comp: 'Championship' },
  { week_number: 7, home: 23, away: 32, comp: 'Championship' },
  { week_number: 7, home: 25, away: 36, comp: 'Championship' },
  { week_number: 7, home: 27, away: 29, comp: 'Championship' },
  { week_number: 8, home: 35, away: 21, comp: 'Championship' },
  { week_number: 8, home: 38, away: 33, comp: 'Championship' },
  { week_number: 8, home: 40, away: 31, comp: 'Championship' },
  { week_number: 8, home: 39, away: 30, comp: 'Championship' },
  { week_number: 8, home: 37, away: 28, comp: 'Championship' },
  { week_number: 8, home: 34, away: 26, comp: 'Championship' },
  { week_number: 8, home: 32, away: 24, comp: 'Championship' },
  { week_number: 8, home: 36, away: 22, comp: 'Championship' },
  { week_number: 8, home: 29, away: 23, comp: 'Championship' },
  { week_number: 8, home: 27, away: 25, comp: 'Championship' },
  { week_number: 9, home: 21, away: 38, comp: 'Championship' },
  { week_number: 9, home: 35, away: 40, comp: 'Championship' },
  { week_number: 9, home: 33, away: 39, comp: 'Championship' },
  { week_number: 9, home: 31, away: 37, comp: 'Championship' },
  { week_number: 9, home: 30, away: 34, comp: 'Championship' },
  { week_number: 9, home: 28, away: 32, comp: 'Championship' },
  { week_number: 9, home: 26, away: 36, comp: 'Championship' },
  { week_number: 9, home: 24, away: 29, comp: 'Championship' },
  { week_number: 9, home: 22, away: 27, comp: 'Championship' },
  { week_number: 9, home: 23, away: 25, comp: 'Championship' },
  { week_number: 10, home: 40, away: 21, comp: 'Championship' },
  { week_number: 10, home: 39, away: 38, comp: 'Championship' },
  { week_number: 10, home: 37, away: 35, comp: 'Championship' },
  { week_number: 10, home: 34, away: 33, comp: 'Championship' },
  { week_number: 10, home: 32, away: 31, comp: 'Championship' },
  { week_number: 10, home: 36, away: 30, comp: 'Championship' },
  { week_number: 10, home: 29, away: 28, comp: 'Championship' },
  { week_number: 10, home: 27, away: 26, comp: 'Championship' },
  { week_number: 10, home: 25, away: 24, comp: 'Championship' },
  { week_number: 10, home: 23, away: 22, comp: 'Championship' },
  { week_number: 11, home: 21, away: 39, comp: 'Championship' },
  { week_number: 11, home: 40, away: 37, comp: 'Championship' },
  { week_number: 11, home: 38, away: 34, comp: 'Championship' },
  { week_number: 11, home: 35, away: 32, comp: 'Championship' },
  { week_number: 11, home: 33, away: 36, comp: 'Championship' },
  { week_number: 11, home: 31, away: 29, comp: 'Championship' },
  { week_number: 11, home: 30, away: 27, comp: 'Championship' },
  { week_number: 11, home: 28, away: 25, comp: 'Championship' },
  { week_number: 11, home: 26, away: 23, comp: 'Championship' },
  { week_number: 11, home: 24, away: 22, comp: 'Championship' },
  { week_number: 12, home: 37, away: 21, comp: 'Championship' },
  { week_number: 12, home: 34, away: 39, comp: 'Championship' },
  { week_number: 12, home: 32, away: 40, comp: 'Championship' },
  { week_number: 12, home: 36, away: 38, comp: 'Championship' },
  { week_number: 12, home: 29, away: 35, comp: 'Championship' },
  { week_number: 12, home: 27, away: 33, comp: 'Championship' },
  { week_number: 12, home: 25, away: 31, comp: 'Championship' },
  { week_number: 12, home: 23, away: 30, comp: 'Championship' },
  { week_number: 12, home: 22, away: 28, comp: 'Championship' },
  { week_number: 12, home: 24, away: 26, comp: 'Championship' },
  { week_number: 13, home: 21, away: 34, comp: 'Championship' },
  { week_number: 13, home: 37, away: 32, comp: 'Championship' },
  { week_number: 13, home: 39, away: 36, comp: 'Championship' },
  { week_number: 13, home: 40, away: 29, comp: 'Championship' },
  { week_number: 13, home: 38, away: 27, comp: 'Championship' },
  { week_number: 13, home: 35, away: 25, comp: 'Championship' },
  { week_number: 13, home: 33, away: 23, comp: 'Championship' },
  { week_number: 13, home: 31, away: 22, comp: 'Championship' },
  { week_number: 13, home: 30, away: 24, comp: 'Championship' },
  { week_number: 13, home: 28, away: 26, comp: 'Championship' },
  { week_number: 14, home: 32, away: 21, comp: 'Championship' },
  { week_number: 14, home: 36, away: 34, comp: 'Championship' },
  { week_number: 14, home: 29, away: 37, comp: 'Championship' },
  { week_number: 14, home: 27, away: 39, comp: 'Championship' },
  { week_number: 14, home: 25, away: 40, comp: 'Championship' },
  { week_number: 14, home: 23, away: 38, comp: 'Championship' },
  { week_number: 14, home: 22, away: 35, comp: 'Championship' },
  { week_number: 14, home: 24, away: 33, comp: 'Championship' },
  { week_number: 14, home: 26, away: 31, comp: 'Championship' },
  { week_number: 14, home: 28, away: 30, comp: 'Championship' },
  { week_number: 15, home: 21, away: 36, comp: 'Championship' },
  { week_number: 15, home: 32, away: 29, comp: 'Championship' },
  { week_number: 15, home: 34, away: 27, comp: 'Championship' },
  { week_number: 15, home: 37, away: 25, comp: 'Championship' },
  { week_number: 15, home: 39, away: 23, comp: 'Championship' },
  { week_number: 15, home: 40, away: 22, comp: 'Championship' },
  { week_number: 15, home: 38, away: 24, comp: 'Championship' },
  { week_number: 15, home: 35, away: 26, comp: 'Championship' },
  { week_number: 15, home: 33, away: 28, comp: 'Championship' },
  { week_number: 15, home: 31, away: 30, comp: 'Championship' },
  { week_number: 16, home: 29, away: 21, comp: 'Championship' },
  { week_number: 16, home: 27, away: 36, comp: 'Championship' },
  { week_number: 16, home: 25, away: 32, comp: 'Championship' },
  { week_number: 16, home: 23, away: 34, comp: 'Championship' },
  { week_number: 16, home: 22, away: 37, comp: 'Championship' },
  { week_number: 16, home: 24, away: 39, comp: 'Championship' },
  { week_number: 16, home: 26, away: 40, comp: 'Championship' },
  { week_number: 16, home: 28, away: 38, comp: 'Championship' },
  { week_number: 16, home: 30, away: 35, comp: 'Championship' },
  { week_number: 16, home: 31, away: 33, comp: 'Championship' },
  { week_number: 17, home: 21, away: 27, comp: 'Championship' },
  { week_number: 17, home: 29, away: 25, comp: 'Championship' },
  { week_number: 17, home: 36, away: 23, comp: 'Championship' },
  { week_number: 17, home: 32, away: 22, comp: 'Championship' },
  { week_number: 17, home: 34, away: 24, comp: 'Championship' },
  { week_number: 17, home: 37, away: 26, comp: 'Championship' },
  { week_number: 17, home: 39, away: 28, comp: 'Championship' },
  { week_number: 17, home: 40, away: 30, comp: 'Championship' },
  { week_number: 17, home: 38, away: 31, comp: 'Championship' },
  { week_number: 17, home: 35, away: 33, comp: 'Championship' },
  { week_number: 18, home: 25, away: 21, comp: 'Championship' },
  { week_number: 18, home: 23, away: 27, comp: 'Championship' },
  { week_number: 18, home: 22, away: 29, comp: 'Championship' },
  { week_number: 18, home: 24, away: 36, comp: 'Championship' },
  { week_number: 18, home: 26, away: 32, comp: 'Championship' },
  { week_number: 18, home: 28, away: 34, comp: 'Championship' },
  { week_number: 18, home: 30, away: 37, comp: 'Championship' },
  { week_number: 18, home: 31, away: 39, comp: 'Championship' },
  { week_number: 18, home: 33, away: 40, comp: 'Championship' },
  { week_number: 18, home: 35, away: 38, comp: 'Championship' },
  { week_number: 19, home: 21, away: 23, comp: 'Championship' },
  { week_number: 19, home: 25, away: 22, comp: 'Championship' },
  { week_number: 19, home: 27, away: 24, comp: 'Championship' },
  { week_number: 19, home: 29, away: 26, comp: 'Championship' },
  { week_number: 19, home: 36, away: 28, comp: 'Championship' },
  { week_number: 19, home: 32, away: 30, comp: 'Championship' },
  { week_number: 19, home: 34, away: 31, comp: 'Championship' },
  { week_number: 19, home: 37, away: 33, comp: 'Championship' },
  { week_number: 19, home: 39, away: 35, comp: 'Championship' },
  { week_number: 19, home: 40, away: 38, comp: 'Championship' },
  { week_number: 20, home: 22, away: 21, comp: 'Championship' },
  { week_number: 20, home: 24, away: 23, comp: 'Championship' },
  { week_number: 20, home: 26, away: 25, comp: 'Championship' },
  { week_number: 20, home: 28, away: 27, comp: 'Championship' },
  { week_number: 20, home: 30, away: 29, comp: 'Championship' },
  { week_number: 20, home: 31, away: 36, comp: 'Championship' },
  { week_number: 20, home: 33, away: 32, comp: 'Championship' },
  { week_number: 20, home: 35, away: 34, comp: 'Championship' },
  { week_number: 20, home: 38, away: 37, comp: 'Championship' },
  { week_number: 20, home: 40, away: 39, comp: 'Championship' },
  { week_number: 21, home: 21, away: 24, comp: 'Championship' },
  { week_number: 21, home: 22, away: 26, comp: 'Championship' },
  { week_number: 21, home: 23, away: 28, comp: 'Championship' },
  { week_number: 21, home: 25, away: 30, comp: 'Championship' },
  { week_number: 21, home: 27, away: 31, comp: 'Championship' },
  { week_number: 21, home: 29, away: 33, comp: 'Championship' },
  { week_number: 21, home: 36, away: 35, comp: 'Championship' },
  { week_number: 21, home: 32, away: 38, comp: 'Championship' },
  { week_number: 21, home: 34, away: 40, comp: 'Championship' },
  { week_number: 21, home: 37, away: 39, comp: 'Championship' },
  { week_number: 22, home: 26, away: 21, comp: 'Championship' },
  { week_number: 22, home: 28, away: 24, comp: 'Championship' },
  { week_number: 22, home: 30, away: 22, comp: 'Championship' },
  { week_number: 22, home: 31, away: 23, comp: 'Championship' },
  { week_number: 22, home: 33, away: 25, comp: 'Championship' },
  { week_number: 22, home: 35, away: 27, comp: 'Championship' },
  { week_number: 22, home: 38, away: 29, comp: 'Championship' },
  { week_number: 22, home: 40, away: 36, comp: 'Championship' },
  { week_number: 22, home: 39, away: 32, comp: 'Championship' },
  { week_number: 22, home: 37, away: 34, comp: 'Championship' },
  { week_number: 23, home: 21, away: 28, comp: 'Championship' },
  { week_number: 23, home: 26, away: 30, comp: 'Championship' },
  { week_number: 23, home: 24, away: 31, comp: 'Championship' },
  { week_number: 23, home: 22, away: 33, comp: 'Championship' },
  { week_number: 23, home: 23, away: 35, comp: 'Championship' },
  { week_number: 23, home: 25, away: 38, comp: 'Championship' },
  { week_number: 23, home: 27, away: 40, comp: 'Championship' },
  { week_number: 23, home: 29, away: 39, comp: 'Championship' },
  { week_number: 23, home: 36, away: 37, comp: 'Championship' },
  { week_number: 23, home: 32, away: 34, comp: 'Championship' },
  { week_number: 24, home: 30, away: 21, comp: 'Championship' },
  { week_number: 24, home: 31, away: 28, comp: 'Championship' },
  { week_number: 24, home: 33, away: 26, comp: 'Championship' },
  { week_number: 24, home: 35, away: 24, comp: 'Championship' },
  { week_number: 24, home: 38, away: 22, comp: 'Championship' },
  { week_number: 24, home: 40, away: 23, comp: 'Championship' },
  { week_number: 24, home: 39, away: 25, comp: 'Championship' },
  { week_number: 24, home: 37, away: 27, comp: 'Championship' },
  { week_number: 24, home: 34, away: 29, comp: 'Championship' },
  { week_number: 24, home: 32, away: 36, comp: 'Championship' },
  { week_number: 25, home: 21, away: 31, comp: 'Championship' },
  { week_number: 25, home: 30, away: 33, comp: 'Championship' },
  { week_number: 25, home: 28, away: 35, comp: 'Championship' },
  { week_number: 25, home: 26, away: 38, comp: 'Championship' },
  { week_number: 25, home: 24, away: 40, comp: 'Championship' },
  { week_number: 25, home: 22, away: 39, comp: 'Championship' },
  { week_number: 25, home: 23, away: 37, comp: 'Championship' },
  { week_number: 25, home: 25, away: 34, comp: 'Championship' },
  { week_number: 25, home: 27, away: 32, comp: 'Championship' },
  { week_number: 25, home: 29, away: 36, comp: 'Championship' },
  { week_number: 26, home: 33, away: 21, comp: 'Championship' },
  { week_number: 26, home: 35, away: 31, comp: 'Championship' },
  { week_number: 26, home: 38, away: 30, comp: 'Championship' },
  { week_number: 26, home: 40, away: 28, comp: 'Championship' },
  { week_number: 26, home: 39, away: 26, comp: 'Championship' },
  { week_number: 26, home: 37, away: 24, comp: 'Championship' },
  { week_number: 26, home: 34, away: 22, comp: 'Championship' },
  { week_number: 26, home: 32, away: 23, comp: 'Championship' },
  { week_number: 26, home: 36, away: 25, comp: 'Championship' },
  { week_number: 26, home: 29, away: 27, comp: 'Championship' },
  { week_number: 27, home: 21, away: 35, comp: 'Championship' },
  { week_number: 27, home: 33, away: 38, comp: 'Championship' },
  { week_number: 27, home: 31, away: 40, comp: 'Championship' },
  { week_number: 27, home: 30, away: 39, comp: 'Championship' },
  { week_number: 27, home: 28, away: 37, comp: 'Championship' },
  { week_number: 27, home: 26, away: 34, comp: 'Championship' },
  { week_number: 27, home: 24, away: 32, comp: 'Championship' },
  { week_number: 27, home: 22, away: 36, comp: 'Championship' },
  { week_number: 27, home: 23, away: 29, comp: 'Championship' },
  { week_number: 27, home: 25, away: 27, comp: 'Championship' },
  { week_number: 28, home: 38, away: 21, comp: 'Championship' },
  { week_number: 28, home: 40, away: 35, comp: 'Championship' },
  { week_number: 28, home: 39, away: 33, comp: 'Championship' },
  { week_number: 28, home: 37, away: 31, comp: 'Championship' },
  { week_number: 28, home: 34, away: 30, comp: 'Championship' },
  { week_number: 28, home: 32, away: 28, comp: 'Championship' },
  { week_number: 28, home: 36, away: 26, comp: 'Championship' },
  { week_number: 28, home: 29, away: 24, comp: 'Championship' },
  { week_number: 28, home: 27, away: 22, comp: 'Championship' },
  { week_number: 28, home: 25, away: 23, comp: 'Championship' },
  { week_number: 29, home: 21, away: 40, comp: 'Championship' },
  { week_number: 29, home: 38, away: 39, comp: 'Championship' },
  { week_number: 29, home: 35, away: 37, comp: 'Championship' },
  { week_number: 29, home: 33, away: 34, comp: 'Championship' },
  { week_number: 29, home: 31, away: 32, comp: 'Championship' },
  { week_number: 29, home: 30, away: 36, comp: 'Championship' },
  { week_number: 29, home: 28, away: 29, comp: 'Championship' },
  { week_number: 29, home: 26, away: 27, comp: 'Championship' },
  { week_number: 29, home: 24, away: 25, comp: 'Championship' },
  { week_number: 29, home: 22, away: 23, comp: 'Championship' },
  { week_number: 30, home: 39, away: 21, comp: 'Championship' },
  { week_number: 30, home: 37, away: 40, comp: 'Championship' },
  { week_number: 30, home: 34, away: 38, comp: 'Championship' },
  { week_number: 30, home: 32, away: 35, comp: 'Championship' },
  { week_number: 30, home: 36, away: 33, comp: 'Championship' },
  { week_number: 30, home: 29, away: 31, comp: 'Championship' },
  { week_number: 30, home: 27, away: 30, comp: 'Championship' },
  { week_number: 30, home: 25, away: 28, comp: 'Championship' },
  { week_number: 30, home: 23, away: 26, comp: 'Championship' },
  { week_number: 30, home: 22, away: 24, comp: 'Championship' },
  { week_number: 31, home: 21, away: 37, comp: 'Championship' },
  { week_number: 31, home: 39, away: 34, comp: 'Championship' },
  { week_number: 31, home: 40, away: 32, comp: 'Championship' },
  { week_number: 31, home: 38, away: 36, comp: 'Championship' },
  { week_number: 31, home: 35, away: 29, comp: 'Championship' },
  { week_number: 31, home: 33, away: 27, comp: 'Championship' },
  { week_number: 31, home: 31, away: 25, comp: 'Championship' },
  { week_number: 31, home: 30, away: 23, comp: 'Championship' },
  { week_number: 31, home: 28, away: 22, comp: 'Championship' },
  { week_number: 31, home: 26, away: 24, comp: 'Championship' },
  { week_number: 32, home: 34, away: 21, comp: 'Championship' },
  { week_number: 32, home: 32, away: 37, comp: 'Championship' },
  { week_number: 32, home: 36, away: 39, comp: 'Championship' },
  { week_number: 32, home: 29, away: 40, comp: 'Championship' },
  { week_number: 32, home: 27, away: 38, comp: 'Championship' },
  { week_number: 32, home: 25, away: 35, comp: 'Championship' },
  { week_number: 32, home: 23, away: 33, comp: 'Championship' },
  { week_number: 32, home: 22, away: 31, comp: 'Championship' },
  { week_number: 32, home: 24, away: 30, comp: 'Championship' },
  { week_number: 32, home: 26, away: 28, comp: 'Championship' },
  { week_number: 33, home: 21, away: 32, comp: 'Championship' },
  { week_number: 33, home: 34, away: 36, comp: 'Championship' },
  { week_number: 33, home: 37, away: 29, comp: 'Championship' },
  { week_number: 33, home: 39, away: 27, comp: 'Championship' },
  { week_number: 33, home: 40, away: 25, comp: 'Championship' },
  { week_number: 33, home: 38, away: 23, comp: 'Championship' },
  { week_number: 33, home: 35, away: 22, comp: 'Championship' },
  { week_number: 33, home: 33, away: 24, comp: 'Championship' },
  { week_number: 33, home: 31, away: 26, comp: 'Championship' },
  { week_number: 33, home: 30, away: 28, comp: 'Championship' },
  { week_number: 34, home: 36, away: 21, comp: 'Championship' },
  { week_number: 34, home: 29, away: 32, comp: 'Championship' },
  { week_number: 34, home: 27, away: 34, comp: 'Championship' },
  { week_number: 34, home: 25, away: 37, comp: 'Championship' },
  { week_number: 34, home: 23, away: 39, comp: 'Championship' },
  { week_number: 34, home: 22, away: 40, comp: 'Championship' },
  { week_number: 34, home: 24, away: 38, comp: 'Championship' },
  { week_number: 34, home: 26, away: 35, comp: 'Championship' },
  { week_number: 34, home: 28, away: 33, comp: 'Championship' },
  { week_number: 34, home: 30, away: 31, comp: 'Championship' },
  { week_number: 35, home: 21, away: 29, comp: 'Championship' },
  { week_number: 35, home: 36, away: 27, comp: 'Championship' },
  { week_number: 35, home: 32, away: 25, comp: 'Championship' },
  { week_number: 35, home: 34, away: 23, comp: 'Championship' },
  { week_number: 35, home: 37, away: 22, comp: 'Championship' },
  { week_number: 35, home: 39, away: 24, comp: 'Championship' },
  { week_number: 35, home: 40, away: 26, comp: 'Championship' },
  { week_number: 35, home: 38, away: 28, comp: 'Championship' },
  { week_number: 35, home: 35, away: 30, comp: 'Championship' },
  { week_number: 35, home: 33, away: 31, comp: 'Championship' },
  { week_number: 36, home: 27, away: 21, comp: 'Championship' },
  { week_number: 36, home: 25, away: 29, comp: 'Championship' },
  { week_number: 36, home: 23, away: 36, comp: 'Championship' },
  { week_number: 36, home: 22, away: 32, comp: 'Championship' },
  { week_number: 36, home: 24, away: 34, comp: 'Championship' },
  { week_number: 36, home: 26, away: 37, comp: 'Championship' },
  { week_number: 36, home: 28, away: 39, comp: 'Championship' },
  { week_number: 36, home: 30, away: 40, comp: 'Championship' },
  { week_number: 36, home: 31, away: 38, comp: 'Championship' },
  { week_number: 36, home: 33, away: 35, comp: 'Championship' },
  { week_number: 37, home: 21, away: 25, comp: 'Championship' },
  { week_number: 37, home: 27, away: 23, comp: 'Championship' },
  { week_number: 37, home: 29, away: 22, comp: 'Championship' },
  { week_number: 37, home: 36, away: 24, comp: 'Championship' },
  { week_number: 37, home: 32, away: 26, comp: 'Championship' },
  { week_number: 37, home: 34, away: 28, comp: 'Championship' },
  { week_number: 37, home: 37, away: 30, comp: 'Championship' },
  { week_number: 37, home: 39, away: 31, comp: 'Championship' },
  { week_number: 37, home: 40, away: 33, comp: 'Championship' },
  { week_number: 37, home: 38, away: 35, comp: 'Championship' },
  { week_number: 38, home: 23, away: 21, comp: 'Championship' },
  { week_number: 38, home: 22, away: 25, comp: 'Championship' },
  { week_number: 38, home: 24, away: 27, comp: 'Championship' },
  { week_number: 38, home: 26, away: 29, comp: 'Championship' },
  { week_number: 38, home: 28, away: 36, comp: 'Championship' },
  { week_number: 38, home: 30, away: 32, comp: 'Championship' },
  { week_number: 38, home: 31, away: 34, comp: 'Championship' },
  { week_number: 38, home: 33, away: 37, comp: 'Championship' },
  { week_number: 38, home: 35, away: 39, comp: 'Championship' },
  { week_number: 38, home: 38, away: 40, comp: 'Championship' }]

hashfix.each do |hash|
  Fixture.create(
    week_number: hash[:week_number],
    home: hash[:home],
    away: hash[:away],
    comp: hash[:comp]
  )
end
