require 'rails_helper'
require 'pry'

RSpec.describe Match::MatchEnd::MatchEndCommentary, type: :model do
  describe 'takes the summary and creates useable summaries' do
    it 'from all current data' do
      fixture_attendance = [{ id: 1, club_home: '1', club_away: '2',
                              week_number: 1, competition: 'Premier League', attendance: 10_000 },
                            { id: 2, club_home: '3', club_away: '4',
                              week_number: 1, competition: 'Premier League', attendance: 10_000 }]

      selection_complete = [{ club_id: '1', player_id: 1, name: 'woolley',
                              total_skill: 85, position: 'gkp', position_detail: 'p',
                              blend: 5, star: 20, fitness: 90, performance: 50 },
                            { club_id: '1', player_id: 2, name: 'woolley',
                              total_skill: 85, position: 'dfc', position_detail: 'p',
                              blend: 5, star: 20, fitness: 90, performance: 52 },
                            { club_id: '1', player_id: 3, name: 'woolley',
                              total_skill: 85, position: 'dfc', position_detail: 'p',
                              blend: 5, star: 20, fitness: 90, performance: 58 },
                            { club_id: '1', player_id: 4, name: 'woolley',
                              total_skill: 85, position: 'dfc', position_detail: 'p',
                              blend: 5, star: 20, fitness: 90, performance: 53 },
                            { club_id: '1', player_id: 5, name: 'woolley',
                              total_skill: 85, position: 'dfc', position_detail: 'p',
                              blend: 5, star: 20, fitness: 90, performance: 52 },
                            { club_id: '1', player_id: 6, name: 'woolley',
                              total_skill: 85, position: 'mid', position_detail: 'p',
                              blend: 4, star: 20, fitness: 90, performance: 54 },
                            { club_id: '1', player_id: 7, name: 'woolley',
                              total_skill: 85, position: 'mid', position_detail: 'p',
                              blend: 5, star: 20, fitness: 90, performance: 56 },
                            { club_id: '1', player_id: 8, name: 'woolley',
                              total_skill: 85, position: 'mid', position_detail: 'p',
                              blend: 6, star: 20, fitness: 90, performance: 52 },
                            { club_id: '1', player_id: 9, name: 'woolley',
                              total_skill: 85, position: 'mid', position_detail: 'p',
                              blend: 7, star: 20, fitness: 90, performance: 51 },
                            { club_id: '1', player_id: 10, name: 'woolley',
                              total_skill: 85, position: 'att', position_detail: 'p',
                              blend: 1, star: 20, fitness: 90, performance: 53 },
                            { club_id: '1', player_id: 11, name: 'woolley',
                              total_skill: 85, position: 'att', position_detail: 'p',
                              blend: 9, star: 20, fitness: 90, performance: 59 },
                            { club_id: '2', player_id: 12, name: 'woolley',
                              total_skill: 85, position: 'gkp', position_detail: 'p',
                              blend: 10, star: 20, fitness: 90, performance: 50 },
                            { club_id: '2', player_id: 13, name: 'woolley',
                              total_skill: 85, position: 'dfc', position_detail: 'p',
                              blend: 4, star: 20, fitness: 90, performance: 52 },
                            { club_id: '2', player_id: 14, name: 'woolley',
                              total_skill: 85, position: 'dfc', position_detail: 'p',
                              blend: 8, star: 20, fitness: 90, performance: 53 },
                            { club_id: '2', player_id: 15, name: 'woolley',
                              total_skill: 85, position: 'dfc', position_detail: 'p',
                              blend: 9, star: 20, fitness: 90, performance: 54 },
                            { club_id: '2', player_id: 16, name: 'woolley',
                              total_skill: 85, position: 'mid', position_detail: 'p',
                              blend: 1, star: 20, fitness: 90, performance: 55 },
                            { club_id: '2', player_id: 17, name: 'woolley',
                              total_skill: 85, position: 'mid', position_detail: 'p',
                              blend: 2, star: 20, fitness: 90, performance: 56 },
                            { club_id: '2', player_id: 18, name: 'woolley',
                              total_skill: 85, position: 'mid', position_detail: 'p',
                              blend: 6, star: 20, fitness: 90, performance: 57 },
                            { club_id: '2', player_id: 19, name: 'woolley',
                              total_skill: 85, position: 'mid', position_detail: 'p',
                              blend: 4, star: 20, fitness: 90, performance: 53 },
                            { club_id: '2', player_id: 19, name: 'woolley',
                              total_skill: 85, position: 'att', position_detail: 'p',
                              blend: 5, star: 20, fitness: 90, performance: 40 },
                            { club_id: '2', player_id: 20, name: 'woolley',
                              total_skill: 85, position: 'att', position_detail: 'p',
                              blend: 5, star: 20, fitness: 90, performance: 30 },
                            { club_id: '2', player_id: 21, name: 'woolley',
                              total_skill: 85, position: 'att', position_detail: 'p',
                              blend: 5, star: 20, fitness: 90, performance: 32 },
                            { club_id: '3', player_id: 22, name: 'woolley',
                              total_skill: 85, position: 'gkp', position_detail: 'p',
                              blend: 5, star: 20, fitness: 90, performance: 50 },
                            { club_id: '3', player_id: 23, name: 'woolley',
                              total_skill: 85, position: 'dfc', position_detail: 'p',
                              blend: 5, star: 20, fitness: 90, performance: 52 },
                            { club_id: '3', player_id: 24, name: 'woolley',
                              total_skill: 85, position: 'dfc', position_detail: 'p',
                              blend: 5, star: 20, fitness: 90, performance: 58 },
                            { club_id: '3', player_id: 25, name: 'woolley',
                              total_skill: 85, position: 'dfc', position_detail: 'p',
                              blend: 5, star: 20, fitness: 90, performance: 53 },
                            { club_id: '3', player_id: 26, name: 'woolley',
                              total_skill: 85, position: 'dfc', position_detail: 'p',
                              blend: 5, star: 20, fitness: 90, performance: 52 },
                            { club_id: '3', player_id: 27, name: 'woolley',
                              total_skill: 85, position: 'mid', position_detail: 'p',
                              blend: 4, star: 20, fitness: 90, performance: 54 },
                            { club_id: '3', player_id: 28, name: 'woolley',
                              total_skill: 85, position: 'mid', position_detail: 'p',
                              blend: 5, star: 20, fitness: 90, performance: 56 },
                            { club_id: '3', player_id: 29, name: 'woolley',
                              total_skill: 85, position: 'mid', position_detail: 'p',
                              blend: 6, star: 20, fitness: 90, performance: 52 },
                            { club_id: '3', player_id: 30, name: 'woolley',
                              total_skill: 85, position: 'mid', position_detail: 'p',
                              blend: 7, star: 20, fitness: 90, performance: 51 },
                            { club_id: '3', player_id: 31, name: 'woolley',
                              total_skill: 85, position: 'att', position_detail: 'p',
                              blend: 1, star: 20, fitness: 90, performance: 53 },
                            { club_id: '3', player_id: 32, name: 'woolley',
                              total_skill: 85, position: 'att', position_detail: 'p',
                              blend: 9, star: 20, fitness: 90, performance: 59 },
                            { club_id: '4', player_id: 33, name: 'woolley',
                              total_skill: 85, position: 'gkp', position_detail: 'p',
                              blend: 10, star: 20, fitness: 90, performance: 50 },
                            { club_id: '4', player_id: 34, name: 'woolley',
                              total_skill: 85, position: 'dfc', position_detail: 'p',
                              blend: 4, star: 20, fitness: 90, performance: 52 },
                            { club_id: '4', player_id: 35, name: 'woolley',
                              total_skill: 85, position: 'dfc', position_detail: 'p',
                              blend: 8, star: 20, fitness: 90, performance: 53 },
                            { club_id: '4', player_id: 36, name: 'woolley',
                              total_skill: 85, position: 'dfc', position_detail: 'p',
                              blend: 9, star: 20, fitness: 90, performance: 54 },
                            { club_id: '4', player_id: 37, name: 'woolley',
                              total_skill: 85, position: 'mid', position_detail: 'p',
                              blend: 1, star: 20, fitness: 90, performance: 55 },
                            { club_id: '4', player_id: 38, name: 'woolley',
                              total_skill: 85, position: 'mid', position_detail: 'p',
                              blend: 2, star: 20, fitness: 90, performance: 56 },
                            { club_id: '4', player_id: 39, name: 'woolley',
                              total_skill: 85, position: 'mid', position_detail: 'p',
                              blend: 6, star: 20, fitness: 90, performance: 57 },
                            { club_id: '4', player_id: 40, name: 'woolley',
                              total_skill: 85, position: 'mid', position_detail: 'p',
                              blend: 4, star: 20, fitness: 90, performance: 53 },
                            { club_id: '4', player_id: 41, name: 'woolley',
                              total_skill: 85, position: 'att', position_detail: 'p',
                              blend: 5, star: 20, fitness: 90, performance: 40 },
                            { club_id: '4', player_id: 42, name: 'woolley',
                              total_skill: 85, position: 'att', position_detail: 'p',
                              blend: 5, star: 20, fitness: 90, performance: 30 },
                            { club_id: '4', player_id: 43, name: 'woolley',
                              total_skill: 85, position: 'att', position_detail: 'p',
                              blend: 5, star: 20, fitness: 90, performance: 32 }]
      summary = [[0,
                  [{ club_id: '1', defense: 170, midfield: 281, attack: 78 },
                   { club_id: '2', defense: 174, midfield: 204, attack: 59 }],
                  [{ club_id: '1', dfc: 2, mid: 3, att: 8 },
                   { club_id: '2', dfc: 1, mid: 4, att: 5 }], 
                  [{ club_id: '1', defense_press: 170, midfield_press: 317, attack_press: 114 },
                   { club_id: '2', defense_press: 174, midfield_press: 204, attack_press: 59 }],
                  { chance: 113, team_chance_roll: 62, random_chance_roll: 41, chance_outcome: 'none' },
                  { on_target_home: 26, on_target_away: 20, on_target_roll: 78, chance_on_target: 'none' },
                  { goal_home: 17, goal_away: 13, goal_roll: 13, goal_scored: 'none' },
                  { assist: 'none', scorer: 'none' }],
                 [0,
                  [{ club_id: '3', defense: 195, midfield: 225, attack: 71 },
                   { club_id: '4', defense: 166, midfield: 212, attack: 73 }],
                  [{ club_id: '3', dfc: 2, mid: 3, att: 8 },
                   { club_id: '4', dfc: 1, mid: 4, att: 5 }],
                  [{ club_id: '3', defense_press: 195, midfield_press: 261, attack_press: 107 },
                   { club_id: '4', defense_press: 166, midfield_press: 212, attack_press: 73 }],
                  { chance: 49, team_chance_roll: 40, random_chance_roll: 25, chance_outcome: 'none' },
                  { on_target_home: 25, on_target_away: 22, on_target_roll: 23, chance_on_target: 'none' },
                  { goal_home: 17, goal_away: 14, goal_roll: 17, goal_scored: 'none' },
                  { assist: 'none', scorer: 'none' }],
                 [1,
                  [{ club_id: '1', defense: 170, midfield: 281, attack: 78 },
                   { club_id: '2', defense: 174, midfield: 204, attack: 59 }],
                  [{ club_id: '1', dfc: 2, mid: 3, att: 8 },
                   { club_id: '2', dfc: 1, mid: 4, att: 5 }],
                  [{ club_id: '1', defense_press: 170, midfield_press: 317, attack_press: 114 },
                   { club_id: '2', defense_press: 174, midfield_press: 204, attack_press: 59 }],
                  { chance: 113, team_chance_roll: 62, random_chance_roll: 41, chance_outcome: 'home' },
                  { on_target_home: 26, on_target_away: 20, on_target_roll: 78, chance_on_target: 'none' },
                  { goal_home: 17, goal_away: 13, goal_roll: 13, goal_scored: 'none' },
                  { assist: 'none', scorer: 'none' }],
                 [1,
                  [{ club_id: '3', defense: 195, midfield: 225, attack: 71 },
                   { club_id: '4', defense: 166, midfield: 212, attack: 73 }],
                  [{ club_id: '3', dfc: 2, mid: 3, att: 8 },
                   { club_id: '4', dfc: 1, mid: 4, att: 5 }],
                  [{ club_id: '3', defense_press: 195, midfield_press: 261, attack_press: 107 },
                   { club_id: '4', defense_press: 166, midfield_press: 212, attack_press: 73 }],
                  { chance: 49, team_chance_roll: 40, random_chance_roll: 25, chance_outcome: 'away' },
                  { on_target_home: 25, on_target_away: 22, on_target_roll: 23, chance_on_target: 'none' },
                  { goal_home: 17, goal_away: 14, goal_roll: 17, goal_scored: 'none' },
                  { assist: 'none', scorer: 'none' }],
                 [2,
                  [{ club_id: '1', defense: 170, midfield: 281, attack: 78 },
                   { club_id: '2', defense: 174, midfield: 204, attack: 59 }],
                  [{ club_id: '1', dfc: 2, mid: 3, att: 8 },
                   { club_id: '2', dfc: 1, mid: 4, att: 5 }],
                  [{ club_id: '1', defense_press: 170, midfield_press: 317, attack_press: 114 },
                   { club_id: '2', defense_press: 174, midfield_press: 204, attack_press: 59 }],
                  { chance: 113, team_chance_roll: 62, random_chance_roll: 41, chance_outcome: 'home' },
                  { on_target_home: 26, on_target_away: 20, on_target_roll: 78, chance_on_target: 'home' },
                  { goal_home: 17, goal_away: 13, goal_roll: 13, goal_scored: 'none' },
                  { assist: 'none', scorer: 'none' }],
                 [2,
                  [{ club_id: '3', defense: 195, midfield: 225, attack: 71 },
                   { club_id: '4', defense: 166, midfield: 212, attack: 73 }],
                  [{ club_id: '3', dfc: 2, mid: 3, att: 8 },
                   { club_id: '4', dfc: 1, mid: 4, att: 5 }],
                  [{ club_id: '3', defense_press: 195, midfield_press: 261, attack_press: 107 },
                   { club_id: '4', defense_press: 166, midfield_press: 212, attack_press: 73 }],
                  { chance: 49, team_chance_roll: 40, random_chance_roll: 25, chance_outcome: 'away' },
                  { on_target_home: 25, on_target_away: 22, on_target_roll: 23, chance_on_target: 'away' },
                  { goal_home: 17, goal_away: 14, goal_roll: 17, goal_scored: 'away' },
                  { assist: 8, scorer: 11 }],
                 [3,
                  [{ club_id: '1', defense: 170, midfield: 281, attack: 78 },
                   { club_id: '2', defense: 174, midfield: 204, attack: 59 }],
                  [{ club_id: '1', dfc: 2, mid: 3, att: 8 },
                   { club_id: '2', dfc: 1, mid: 4, att: 5 }],
                  [{ club_id: '1', defense_press: 170, midfield_press: 317, attack_press: 114 },
                   { club_id: '2', defense_press: 174, midfield_press: 204, attack_press: 59 }],
                  { chance: 113, team_chance_roll: 62, random_chance_roll: 41, chance_outcome: 'home' },
                  { on_target_home: 26, on_target_away: 20, on_target_roll: 78, chance_on_target: 'home' },
                  { goal_home: 17, goal_away: 13, goal_roll: 13, goal_scored: 'home' },
                  { assist: 2, scorer: 6 }],
                 [3,
                  [{ club_id: '3', defense: 195, midfield: 225, attack: 71 },
                   { club_id: '4', defense: 166, midfield: 212, attack: 73 }],
                  [{ club_id: '3', dfc: 2, mid: 3, att: 8 },
                   { club_id: '4', dfc: 1, mid: 4, att: 5 }],
                  [{ club_id: '3', defense_press: 195, midfield_press: 261, attack_press: 107 },
                   { club_id: '4', defense_press: 166, midfield_press: 212, attack_press: 73 }],
                  { chance: 49, team_chance_roll: 40, random_chance_roll: 25, chance_outcome: 'away' },
                  { on_target_home: 25, on_target_away: 22, on_target_roll: 23, chance_on_target: 'away' },
                  { goal_home: 17, goal_away: 14, goal_roll: 17, goal_scored: 'away' },
                  { assist: 8, scorer: 11 }]]

      Template.create(commentary_type: 'match_general', text: '{team} applies pressure in the midfield, but fails to find a way through the opponents defense')
      Template.create(commentary_type: 'match_chance', text: '{team} have a chance but its off target')
      Template.create(commentary_type: 'match_chance_tar', text: '{team} have a chance but the keeper saves')
      Template.create(commentary_type: 'match_goal', text: '{team} score a goal, {assister} with the assist and {scorer} with the goal')

      allow_any_instance_of(Kernel).to receive(:rand).with(20..30).and_return(25)
      allow_any_instance_of(Kernel).to receive(:rand).with(70..80).and_return(75)

      Match::MatchEnd::MatchEndCommentary.new(summary, selection_complete, fixture_attendance).call

      binding.pry
    end
  end
end
