name: Run RSpec Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'  # Match your Ruby version
          bundler-cache: true

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          gem install bundler --version 2.3.0 # Ensuring the correct Bundler version
          bundle install --verbose  # Run bundle with verbose output to get more details on failures

      # Step 4: Run RSpec tests
      - name: Run RSpec tests
        run: |
          bundle exec rspec --verbose
