name: Rails Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependencies
        run: bundle install

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for PostgreSQL to be ready..."
            sleep 3
          done

      - name: Set up database credentials
        env:
          DB_USERNAME: postgres
          DB_PASSWORD: postgres
        run: |
          echo "DATABASE_USERNAME=${DB_USERNAME}" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=${DB_PASSWORD}" >> $GITHUB_ENV

      - name: Run tests
        run: bundle exec rspec
