name: Run RSpec Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true

      - name: Set Rails master key
        run: echo "${{ secrets.RAILS_MASTER_KEY }}" > config/master.key

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Precompile Rails application
        run: |
          RAILS_ENV=test bundle exec rails assets:precompile

      - name: Run RSpec tests
        run: |
          bundle exec rspec
