name: Run RSpec Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler --version 2.3.0 e
          bundle install

      - name: Run RSpec tests
        run: |
          bundle exec rspec
