name: Run RSpec Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.2'
          bundler-cache: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version compatible with your project

      - name: Install JavaScript dependencies
        run: npm install

      - name: Install Ruby dependencies
        run: |
          gem install bundler
          bundle install

      - name: Set Rails Master Key
        env:
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: echo "RAILS_MASTER_KEY=${{ secrets.RAILS_MASTER_KEY }}" >> $GITHUB_ENV

      - name: Set up database
        run: |
          RAILS_ENV=test bundle exec rails db:create
          RAILS_ENV=test bundle exec rails db:migrate

      - name: Precompile Rails assets
        run: |
          RAILS_ENV=test bundle exec rails assets:precompile

      - name: Run RSpec tests
        run: |
          bundle exec rspec
