name: Rails Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ftw_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Set up database credentials
        env:
          DB_USERNAME: your_db_username
          DB_PASSWORD: your_db_password
        run: |
          echo "DATABASE_USERNAME=${DB_USERNAME}" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=${DB_PASSWORD}" >> $GITHUB_ENV

      - name: Create and setup database
        env:
          RAILS_ENV: test
          USERNAME: ${{ secrets.DB_USERNAME }}
          PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: |
          bundle exec rails db:create
          bundle exec rails db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
        run: bundle exec rspec
